### ISSUE TITLE
UNipepti pepidome clustering is nor=t working on the web page

### ISSUE THREAD

**Issue by samehmgd** [unipept/unipept#1064]
when trying to cluster peptides on the web page .. tooks long time with out any result
tried from different network and pcs ,, same

**Comment by bmesuere** [comment]
Thank you for the report, we will look into it.

**Comment by bmesuere** [comment]
@samehmgd can you give me a little more information on what exactly you're trying to do and in which browser? Everything seems to work here.

**Comment by samehmgd** [comment]
Any submitted tasks on peptide clustering keeps searching for long time without returning a results. Could it be security issues, internet speed or chrome browser?? Sameh magdeldin DVSc., 2Ph.DHead of proteomics and metabolomics unitChildren Cancer Hospital 57357Www.57357.org/proteomics-unit -------- Original message --------From: Bart Mesuere <notifications@github.com>Date: Wed, May 6, 2020, 2:00 PMTo: unipept/unipept <unipept@noreply.github.com>Cc: samehmgd <samehmagd@yahoo.com>, Mention <mention@noreply.github.com>Subject: Re: [unipept/unipept] UNipepti pepidome clustering is nor=t working on the web page (#1064)
@samehmgd can you give me a little more information on what exactly you're trying to do and in which browser? Everything seems to work here.

**Comment by bmesuere** [comment]
So if I go to https://unipept.ugent.be/peptidomeclustering, scroll down and click on the red trash icon, I get this view:
![image](https://user-images.githubusercontent.com/481872/81271218-1f951680-904c-11ea-8ffa-6264fbf67183.png)

If I then select a few proteomes from the list on the left and wait a bit I get this:
![image](https://user-images.githubusercontent.com/481872/81271380-4a7f6a80-904c-11ea-82d8-67cbf7877ce8.png)

If I then scroll up, I see this clustered view:
![image](https://user-images.githubusercontent.com/481872/81271441-5ff49480-904c-11ea-891b-33d51f9f28d7.png)

At which step exactly are you stuck? Which browser are you using?

**Comment by samehmgd** [comment]
thanks. it seems to be a security issue from our side
