### ISSUE TITLE
Strip #-symbols from input

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#115]
PRIDE sometimes returns peptides containing a # representing an oxidation of methionine. According to Griet, we should strip the #-symbols and search the database without them.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/115) by @bmesuere on Thu Mar 21 2013 at 15:12._
_Closed by @bmesuere on Sun Jun 15 2014 at 23:04._

**Comment by bmesuere** [comment]
Original email from Griet

> Dag Bart,
> 
> Ik heb eens gekeken naar het inlezen van de data uit pride, momenteel staan er veel sequenties in de niet gevonden peptiden met een #
> 
> vb pride 8217
> 
> ADDKVYPGEQYTY
> ADDKVYPGEQYTYM#LLATEEQSPGEGDGNCVTR
> ADGESCSASM#M#YQEGK
> ADGESCSASM#MYQEGK
> ADGESCSASMM#YQEGK
> ADKPETTKEQLGEFYEALDCLR
> AEM#ADQAAAWLTR
> AFNSTLPTM#AQM#EK
> AFNSTLPTM#AQMEK
> AFNSTLPTMAQM#EK
> AGAFLGLTNVAVM#NLSGNCLR
> AGDFLEANYM#NLQR
> ALFYETQPSLWAESESLLKPLANVTLTCQAR
> ALM#DGASQLM#GENR
> ALM#DGASQLMGENR
> 
> volgens mij zijn dit allemaal oxidaties van methionine, die eigenlijk verwijderd kunnen worden, dan zullen er minder in de niet gevonden lijst staan.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/115#issuecomment-9989) by @bmesuere on Tue Jun 03 2014 at 22:07._

**Comment by pdawyndt** [comment]
@bmesuere : I ran the above dataset (without the hashes) through the multi-peptide search. There were four tryptic peptides that were not matched in Unipept

```
ADKPETTK (100% BLAST match)
ALFYETQPSLWAESESLLKPLANVTLTCQAR
ALMDGASQLMGENR (100% BLAST match)
VYPGEQYTY (100% BLAST match)
```

Three of those had multiple 100% BLAST hits (100% identity, 100% coverage). So the question is why these sequences have not been matched in Unipept. Several of the hits were in GenBank before we last indexed Uniprot. Question is whether these sequences are in Uniprot?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/115#issuecomment-10083) by @pdawyndt on Sun Jun 15 2014 at 20:53._

**Comment by bmesuere** [comment]
Does this have anything to do with the filtering of the hashes?

The reason for not finding them is they are not tryptic peptides in the BLAST matches.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/115#issuecomment-10084) by @bmesuere on Sun Jun 15 2014 at 21:06._

**Comment by pdawyndt** [comment]
Has nothing to do with the hashes, but since they come from proteomics experiments, I would expect them to be tryptic peptides.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/115#issuecomment-10085) by @pdawyndt on Sun Jun 15 2014 at 22:36._

**Comment by bmesuere** [comment]
I checked the source files in PRIDE and all blast matches. None of them is a tryptic peptide, so none could be found by unipept.
The origin of the first peptide is `ADKPETTKEQLGEFYEALDCLR` of which we do pick up the second part.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/115#issuecomment-10086) by @bmesuere on Sun Jun 15 2014 at 23:04._
