### ISSUE TITLE
linkout to PRIDE, NIST, PeptideAtlas, IEDB 

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#122]
From a peptide page, we can linkout (or fetch asynchronously) to the following repositories:
- PRIDE (Vizcaíno et al., 2013)
- NIST Peptide Libraries (Stein and Rudnick, 2009)
- PeptideAtlas (Desiere et al., 2006)
- Immune Epitope Database (IEDB) (Vita et al., 2009) 

Similar to the review Bioinformatics paper, this can be done using the search interfaces of these repositories.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/122) by @pdawyndt on Wed Apr 10 2013 at 16:31._
_Closed by @bmesuere on Wed Jul 16 2014 at 20:41._

**Comment by bmesuere** [comment]
The NIST website is offline and IEDB doesn't allow searches based on uniprot_id


_[Original comment](https://github.ugent.be/unipept/unipept/issues/122#issuecomment-10290) by @bmesuere on Wed Jul 16 2014 at 20:42._
