### ISSUE TITLE
wrong display of pancore plot when first loading genomes from Sinorhizobium meliloti

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#126]
when first loading the genomes of Sinorhizobium meliloti, the pancore plot goes astray due to reorderings of genomes while loading; this disappears after one of the genomes is relocated manually; also the "izo" in Sinorhizobium is not properly displayed on the x-axis of the plot.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/126) by @pdawyndt on Wed Apr 10 2013 at 16:46._
_Closed by @bmesuere on Wed May 29 2013 at 20:01._

**Comment by bmesuere** [comment]
fixed in 8cbecab8e19f328606a370f35fc79e25106c0930


_[Original comment](https://github.ugent.be/unipept/unipept/issues/126#issuecomment-3550) by @bmesuere on Wed May 29 2013 at 20:01._
