### ISSUE TITLE
options for sorting genomes in pancore

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#128]
possible strategies for ranking the genomes
- absolute ranking
  - minimal area in between core and pan curves (greedy -- slow)
  - minimal area in between core and pan curves (optimal -- very slow)
- relative ranking (first genome remains fixed and serves as a reference)
  - distance order (very fast)
  - maximal core (fast): can be done left to right or right to left (the latter first needs to compute the right pan/core)
  - minimal pan (fast): can be done left to right or right to left (the latter first needs to compute the right pan/core)

possible strategies for selecting the first genome if relative ranking is chosen
- fixed (keep manual selection - direct)
- maximal number of peptides (very fast)
- minimal number of peptides (very fast)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/128) by @pdawyndt on Wed Apr 10 2013 at 20:21._
_Closed by @bmesuere on Tue Jul 30 2013 at 14:08._

**Comment by bmesuere** [comment]
implemented:
- sort by name
- sort by size


_[Original comment](https://github.ugent.be/unipept/unipept/issues/128#issuecomment-4214) by @bmesuere on Wed Jul 17 2013 at 17:23._

**Comment by bmesuere** [comment]
added:
- maximize core
- minimize pan
- optimal (minimal distance between pan and core)
  These methods all start from the current first node and calculate the optimal next one.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/128#issuecomment-4228) by @bmesuere on Tue Jul 30 2013 at 14:08._
