### ISSUE TITLE
NCBI taxonomy cleanup: main drainage metagenome

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#135]
The name "main drainage metagenome" should be invalidated from the NCBI taxonomy, as it also spoils the LCA computation of this example:

http://unipept.ugent.be/sequences/GITAIQMDIK/true

_[Original issue](https://github.ugent.be/unipept/unipept/issues/135) by @pdawyndt on Sat May 11 2013 at 12:52._
_Closed by @bmesuere on Sat May 11 2013 at 13:48._

**Comment by bmesuere** [comment]
Already invalidated in scruffy


_[Original comment](https://github.ugent.be/unipept/unipept/issues/135#issuecomment-2167) by @bmesuere on Sat May 11 2013 at 13:48._
