### ISSUE TITLE
check this website: The Peptide Resource Page

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#137]
http://www.peptideresource.com/

_[Original issue](https://github.ugent.be/unipept/unipept/issues/137) by @pdawyndt on Mon May 13 2013 at 16:23._
_Closed by @bmesuere on Mon Feb 01 2016 at 14:01._

**Comment by bmesuere** [comment]
web page is offline


_[Original comment](https://github.ugent.be/unipept/unipept/issues/137#issuecomment-24500) by @bmesuere on Mon Feb 01 2016 at 14:01._
