### ISSUE TITLE
test skyline software

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#140]
This software can select from a set of potential markers, compute good candidate selctions

_[Original issue](https://github.ugent.be/unipept/unipept/issues/140) by @pdawyndt on Wed May 15 2013 at 15:10._
_Closed by @bmesuere on Mon Feb 01 2016 at 14:03._

**Comment by pdawyndt** [comment]
https://brendanx-uw1.gs.washington.edu/labkey/project/home/software/Skyline/begin.view


_[Original comment](https://github.ugent.be/unipept/unipept/issues/140#issuecomment-2290) by @pdawyndt on Wed May 15 2013 at 15:29._

**Comment by bmesuere** [comment]
After our recent conversations with Lennart, this doesn't seem relevant anymore.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/140#issuecomment-24501) by @bmesuere on Mon Feb 01 2016 at 14:03._
