### ISSUE TITLE
javascript phylogenetic tree software

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#142]
Try out the following library for drawing phylogenetic trees: http://www.jsphylosvg.com

publication: http://www.plosone.org/article/info:doi/10.1371/journal.pone.0012267

_[Original issue](https://github.ugent.be/unipept/unipept/issues/142) by @pdawyndt on Wed May 22 2013 at 12:24._
_Closed by @bmesuere on Thu May 08 2014 at 19:56._

**Comment by bmesuere** [comment]
d3 implementation of phylogenetic trees: http://bl.ocks.org/bmesuere/5643069
might use inspiration from jsphylosvg


_[Original comment](https://github.ugent.be/unipept/unipept/issues/142#issuecomment-3537) by @bmesuere on Fri May 24 2013 at 14:18._
