### ISSUE TITLE
Having empty toxonomy information on api unipept website

### ISSUE THREAD

**Issue by simaafshar** [unipept/unipept#1506]
Hello,
I have an issue with using your database. Whan I am calling "http://api.unipept.ugent.be/api/v1/taxonomy.json?input[]=817&extra=true&names=true", some items like  "species_name","genus_name", "family_name",'order_name' and "class_name" are empty, however; regarding the document at your site those should not be empty. 
" https://unipept.ugent.be/apidocs/taxonomy"I would appreciate it if you could let me know how I can fix it.
Thank you in advance,
Sima

**Comment by pverscha** [comment]
Hi Sima,

Thank you for contacting us. I was able to reproduce your issue and I have created a fix for the problem. The fix will be deployed as soon as possible and I will let you know once it's done.

Please note that this issue only occurs with the old version of our API (v1), if you don't specifically rely on the old ranking order from v1 of our API, I would suggest you to move to v2 of the API, which is accessible from this endpoint: `http://api.unipept.ugent.be/api/v2/taxonomy.json?input=817&extra=true&names=true`

**Comment by pverscha** [comment]
Hi Sima,

A new version of the API has been deployed on our server and your issue should be fixed. Please contact us again in case you still encounter problems.
