### ISSUE TITLE
Splitting the frontend and backend

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#1515]
In the coming months, we will have to invest some time to upgrade the underlying frameworks of Unipept. The frontend will move to vue 3 and the new vuetify release, the backend needs a rails update. This rails update, however, will also require changes to the bundling of the frontend since the webpacker config (again) changes.

This might be the time to split the current rails application into a separate app for the frontend and one for the backend. They could live in the same repository in separate directories in the root. Before proceeding, it's worth checking if such migration would be possible (solutions must be found for the current static pages that aren't migrated to vue yet, for the svg to png conversion, for the news page, the sample datasets, etc).

A potential way forward is to 
1. create an entirely new vue 3 app (using vite or webpack) in the frontend directory and try to reuse as much code as possible
2. create an entirely new rails app using the api flag (to get rid of unneeded view settings and dependencies) and reuse as much model and controller code as possible

**Comment by pverscha** [comment]
I support this proposition. A few remarks / additional comments:

* If we decide to use Vue 3 for the frontend, we should first update all of the components from the `unipept-web-components` repository to Vue 3 (using the latest Vuetify version). This needs to be done anyway, but it will take a significant amount of time which might push this proposition a bit further in time.

* Converting SVG to PNG images can be performed client-side using the excelling [Canvg-package](https://www.npmjs.com/package/canvg). We are already using this package for the Unipept Desktop application and it works excellent.

**Comment by bmesuere** [comment]
Do you propose to first migrate the current Vue 2 front-end out of the rails application and only later upgrade to Vue 3?
