### ISSUE TITLE
check why some complete genomes are missing in the pan/core plot

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#155]
The pan/core plot of Acinetobacter only contains 12 complete genomes, whereas NCBI genome lists [15 complete genomes](http://www.ncbi.nlm.nih.gov/genome/genomes/403)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/155) by @pdawyndt on Fri Aug 30 2013 at 14:36._
_Closed by @bmesuere on Thu May 08 2014 at 18:00._

**Comment by bmesuere** [comment]
The list on that website isn't the same as the list on ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt
For example, on the website Acinetobacter baumannii AC12 is marked as complete, but on the ftp-server it's listed as:

```
Acinetobacter baumannii AC12    1198108 PRJNA168112 168112  Proteobacteria  Gammaproteobacteria 3.84831 38.9    -   -   -   -   ALAM01  -   3688    3643    2012/07/30  2014/01/08  Scaffolds or contigs    Universiti Sultan Zainal Abidin -   -   -   -
```

I'm currently also updating the genomes list which should increase the number of completed genomes from 5400 to 6000+


_[Original comment](https://github.ugent.be/unipept/unipept/issues/155#issuecomment-9367) by @bmesuere on Thu May 08 2014 at 18:00._
