### ISSUE TITLE
add option to include/exclude plasmids from pan/core plot

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#156]
_[Original issue](https://github.ugent.be/unipept/unipept/issues/156) by @pdawyndt on Fri Aug 30 2013 at 14:37._
_Closed by @bmesuere on Sun Apr 20 2014 at 14:36._

**Comment by bmesuere** [comment]
won't fix


_[Original comment](https://github.ugent.be/unipept/unipept/issues/156#issuecomment-8797) by @bmesuere on Sun Apr 20 2014 at 14:35._
