### ISSUE TITLE
add genomes by similarity

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#192]
The current way of adding genomes to the unique peptide finder and the genome clustering only allows to select genomes by name. It would be nice to allow selection by similarity, in order to locate neighbouring genomes that have been misidentified or have been identified at a less specific taxonomic level. Instead of showing the taxonomic tree, in this case a list could be shown of the closest genomes to the ones already selected. Closeness could be measured as the maximal, minimal or average similarity of a genome to all genomes already selected.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/192) by @pdawyndt on Tue Nov 12 2013 at 14:17._

**Comment by bmesuere** [comment]
Adding this as a feature is not possible as it would require precalculating all pairwise similarities (14000^2). Doing this once (offline), however is possible and might be interesting:
- this can be done without using the web application by using internal API calls (or the needed data can be downloaded from a database dump)
- calculate a similarity matrix of all 14K proteomes.
- generate a phylogenetic tree of all proteomes
- automatically search for closely related species/misclassified proteomes

@pdawyndt this might be a possible computational biology project?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/192#issuecomment-24502) by @bmesuere on Mon Feb 01 2016 at 14:12._
