### ISSUE TITLE
improve visualisation of sim-graph

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#207]
Greenish colour is a bit ugly, and line thickness should be chosen more carefully.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/207) by ghost on Fri Dec 13 2013 at 09:50._
_Closed by @bmesuere on Sun Apr 20 2014 at 14:40._

**Comment by bmesuere** [comment]
Any suggestions for further improving it?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7158) by @bmesuere on Sat Dec 14 2013 at 20:13._

**Comment by bmesuere** [comment]
I've removed the ending circles and made the entire tree black.

![like this](https://github.ugent.be/github-enterprise-assets/0000/0036/0000/0097/cb858e66-6740-11e3-8b7d-4f96dc5726e4.png)
@pdawyndt, @bmesuere any more suggestions?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7186) by ghost on Tue Dec 17 2013 at 18:30._

**Comment by bmesuere** [comment]
I (personally) don't like the black lines. Maybe `#333333` (the text color in bootstrap) is a little "softer".
Also, the axis labels are a bit messed up due to the new scaling. 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7187) by @bmesuere on Tue Dec 17 2013 at 22:36._

**Comment by bmesuere** [comment]
I changed the color and rotated the labels, so there is no more overlap.

See:
![improved](https://github.ugent.be/github-enterprise-assets/0000/0036/0000/0098/5505f0ba-67e9-11e3-8bd4-4e756a60f289.png)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7194) by ghost on Wed Dec 18 2013 at 14:36._

**Comment by pdawyndt** [comment]
- why not root the tree at the leftmost position of the scale?
- I would prefer less horizontal lines (too much distraction), in this case I would be happy only to have lines for multiples of 0.1


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7208) by @pdawyndt on Thu Dec 19 2013 at 18:14._

**Comment by bmesuere** [comment]
- switch to 6 scale lines
- also use blur filter for inactive tree


_[Original comment](https://github.ugent.be/unipept/unipept/issues/207#issuecomment-7211) by @bmesuere on Fri Dec 20 2013 at 11:27._
