### ISSUE TITLE
correct representation of LCA

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#211]
- LCA of Bacillus cereus and B. anthracis is represented as "undefined"

_[Original issue](https://github.ugent.be/unipept/unipept/issues/211) by @pdawyndt on Fri Jan 17 2014 at 10:31._
_Closed by @bmesuere on Fri Jan 17 2014 at 11:47._

**Comment by bmesuere** [comment]
fixed in e295080195454b2a616937b895f620083dafadf1


_[Original comment](https://github.ugent.be/unipept/unipept/issues/211#issuecomment-7330) by @bmesuere on Fri Jan 17 2014 at 11:47._
