### ISSUE TITLE
implement prot2pept and peptfilter

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#231]
add following commands to unipept suite; implement them as separate commands next to the unipept commands, since they don't require access to the unipept database
- `prot2pept`: cleaves proteins from stdin (one protein on each line) into a series of peptide (one peptide on a line); may have some built-in cleavage patterns (trypsin by default), but could also take a regular expression used to cleave proteins
- `peptfilter`: filters a given list of peptides (one peptide on each line) using a series of criteria: 
  - `minlen`: minimum length
  - `maxlen`: maximum length
  - `contains`: should include a given list of residues
  - `lacks`: should not include any of the listed residues

This should to set up pipelines like

```
echo <protein> | prot2pept | peptfilter --minlen 5 --maxlen 50 | unipept pept2lca
```

Description of options: http://www.spoj.com/PROGPY/problems/PROG0165/

_[Original issue](https://github.ugent.be/unipept/unipept/issues/231) by @pdawyndt on Fri Mar 21 2014 at 12:39._
_Closed by an unknown user on Mon Mar 31 2014 at 21:53._

**Comment by bmesuere** [comment]
contains -> every single one should be present
lacks -> no one can be present


_[Original comment](https://github.ugent.be/unipept/unipept/issues/231#issuecomment-8348) by ghost on Tue Mar 25 2014 at 10:42._
