### ISSUE TITLE
bigger database, less hits ???

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#251]
in the Unipept paper, we got 16 hits for the example peptide that we used; while rereading the paper, I rerun the single peptide analysis for this peptide with the current version of unipept, and although the total number of uniprot peptides has doubled since we wrote the paper, we didn't fare more hits but one less !!! something to look into

_[Original issue](https://github.ugent.be/unipept/unipept/issues/251) by @pdawyndt on Fri Apr 25 2014 at 09:35._
_Closed by @bmesuere on Fri May 09 2014 at 15:59._

**Comment by bmesuere** [comment]
Only _Abiotrophia defectiva_ ATCC 49176 is missing. I downloaded all proteins for this organism (http://beta.uniprot.org/uniprot/?query=abiotrophia+defectiva+atcc+49176&sort=score&fil=) and couldn't find the peptide in the fasta file. The sequence was probably updated or removed from uniprot.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/251#issuecomment-9411) by @bmesuere on Fri May 09 2014 at 15:59._
