### ISSUE TITLE
unipept taxa2lca produces error

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#258]
error when running `taxa2lca` subcommand

```
$ echo -ne "1\n816\n816\n" | unipept taxa2lca
API endpoint gave an error, exiting.  
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/258) by @pdawyndt on Mon Apr 28 2014 at 19:51._
_Closed by an unknown user on Mon May 12 2014 at 08:29._

**Comment by bmesuere** [comment]
The issue here is that Taxon with id 1 has no lineage. @bmesuere is this normal and should I just filter out those without lineage? Or is this an actual error?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9032) by ghost on Tue Apr 29 2014 at 19:08._

**Comment by bmesuere** [comment]
The taxon with id 1 is root (no rank) and has indeed no lineage. Our database only contains named ranks, so root itself also never occurs within the lineage of another taxon.
- filtering id 1 would probably result in incorrect results, so this is not a great solution.
- handling root as a special case in the lca algorithm might solve this problem, but:
- unipept now only includes the lineages for the taxa present in uniprot entries. When you allow to query for any taxon id (which is the case for taxa2lca), this might be problem.

proposed solution:
- short term: add special case for root + add better error handling and error message for other id's without lineage.
- long term: when the lineage of a taxon is not found in the database, calculate it and add it to the database. Lineage invalidation should be taken into account.

@pdawyndt do you agree?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9034) by @bmesuere on Tue Apr 29 2014 at 19:58._

**Comment by bmesuere** [comment]
I've deployed and pushed a fix which will ignore missing lineages. 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9041) by ghost on Tue Apr 29 2014 at 22:11._

**Comment by pdawyndt** [comment]
Apparently, the root element of the NCBI Taxonomy has [taxon_id 131567](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=131567&lvl=3&lin=f&keep=1&srchmode=1&unlock) and is called `cellular organism`. It indeed has no rank, which is probably the reason why it is invalidated during the build-up of Unipept. I don't know whether or not it is relevant that this would be treated as a special case during invalidation, or whether keeping this taxonomic node as a valid node might have serious implications for the current code base.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9333) by @pdawyndt on Wed May 07 2014 at 21:19._

**Comment by pdawyndt** [comment]
@bmesuere: Long term policy: I guess that precomputing the lineages for all taxon IDs in the NCBI Taxonomy should not take too much time, so instead of taking the burden of a lazy computation scheme, I would have them all precomputed.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9334) by @pdawyndt on Wed May 07 2014 at 21:22._

**Comment by pdawyndt** [comment]
@bmesuere `@tvwillem` : I agree with the short term policy


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9336) by @pdawyndt on Wed May 07 2014 at 22:46._

**Comment by pdawyndt** [comment]
`@tvwillem` : I still observe two problems with taxon ID 1:

```
$ unipept -v
0.3.5
$ echo 816 | unipept taxa2lca
taxon_id,taxon_name,taxon_parent_id,taxon_rank
816,Bacteroides,815,genus
$ echo 1 | unipept taxa2lca
API request failed! log can be found in /users/p/pdawyndt/unipept.log
$ echo -e "1\n816" | unipept taxa2lca
taxon_id,taxon_name,taxon_parent_id,taxon_rank
816,Bacteroides,815,genus
```

There's still an "API request failed" error message, and in the latter case, the LCA should technically be taxon ID 1, not taxon ID 816.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9481) by @pdawyndt on Sun May 11 2014 at 21:29._

**Comment by bmesuere** [comment]
@pdawyndt indeed, I incorrectly ignored taxon_id 1. This is fixed now (deploy will happen when your analysis is done)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/258#issuecomment-9485) by ghost on Mon May 12 2014 at 08:26._
