### ISSUE TITLE
command line tools should not use buffering

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#259]
seemingly command line tools use buffering, as seen from running for example the `prot2pept` command

```
$ fasta2prot < patient_TS19_CDS | prot2pept
```

apparently, the list of peptides is first constructed in memory, and only written to stdout after the whole list has been constructed; this not only has a serious memory footprint, but also prevents successive parts of a pipeline to be run in parallel

_[Original issue](https://github.ugent.be/unipept/unipept/issues/259) by @pdawyndt on Mon Apr 28 2014 at 19:58._
_Closed by an unknown user on Tue Apr 29 2014 at 19:02._

**Comment by bmesuere** [comment]
Fixed in unipept 0.2.7


_[Original comment](https://github.ugent.be/unipept/unipept/issues/259#issuecomment-9031) by ghost on Tue Apr 29 2014 at 19:02._
