### ISSUE TITLE
performance measurement of command line tools

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#260]
- break proteins from shotgun metagenomics dataset into peptides, and lookup LCA for each individual peptide

```
$ fasta2prot < patient_TS19_CDS | prot2pept | peptfilter | sort | uniq | unipept pept2lca -e
```

number of proteins: 363716 (processed in 0m0.949s)
number of peptides: 2784140 (processed in 0m12.430s (was 0m26.967s))
number of peptides after filtering: 1685570 (processed in 0m16.343s (was 0m38.717s))
number of unique peptides after filtering: 1137246 (processed in 0m17.378s (was 0m49.794s))
lookup of LCAs: ??? (could not be determined due to an error in unipept pept2lca)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/260) by @pdawyndt on Mon Apr 28 2014 at 20:03._
_Closed by an unknown user on Sun May 11 2014 at 13:52._

**Comment by bmesuere** [comment]
I've changed the batch size to 10, so you should see more gradual output now. (see unipept 0.2.8)
I've also improved the speed of pept2lca (I performed an unnecessary join). 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9042) by ghost on Tue Apr 29 2014 at 22:21._

**Comment by pdawyndt** [comment]
error

```
$ time fasta2prot < patient_TS19_CDS | head -n2000 | prot2pept | peptfilter | sort | uniq | unipept pept2lca 
Exception IOError: IOError(32, 'Broken pipe') in <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'> ignored
API endpoint gave an error, exiting.

real    0m0.310s
user    0m0.372s
sys     0m0.044s
```

performance has increased; at least, now I can process the first 1000 DNA reads in no time

```
$ time fasta2prot < patient_TS19_CDS | head -n1000 | prot2pept | peptfilter | sort | uniq | unipept pept2lca                      | wc -l
API endpoint gave an error, exiting.
0

real    0m0.318s
user    0m0.284s
sys     0m0.060s
```

but after a while I always get the same error message

```
API endpoint gave an error, exiting.
```

and none of the unipept analysis works anymore; is this a server-related issue?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9048) by @pdawyndt on Wed Apr 30 2014 at 09:47._

**Comment by pdawyndt** [comment]
could it be a problem with a cache; if following upon the above analysis I start a request that is new (note that I added the -e option), it seems to work again, but not if I try to repeat an analysis (that uses cached results)

```
$ fasta2prot < patient_TS19_CDS | head -n10 | prot2pept | peptfilter | sort | uniq | unipept pept2lca
API endpoint gave an error, exiting.
$ fasta2prot < patient_TS19_CDS | head -n10 | prot2pept | peptfilter | sort | uniq | unipept pept2lca -e
sequence,taxon_id,taxon_name,taxon_parent_id,taxon_rank
AVADGR,1,root,1,no rank
DLHNEK,1,root,1,no rank
FFALK,1,root,1,no rank
FHAGK,1,root,1,no rank
NDGAR,1,root,1,no rank
NEGLGK,1,root,1,no rank
NLTSGFK,1,root,1,no rank
NQDSGR,1,root,1,no rank
SGYGNR,1,root,1,no rank
SPEGK,1,root,1,no rank
VVELK,1,root,1,no rank
ALFLDTPEPR,816,Bacteroides,815,genus
GEVLGGVGSTGK,816,Bacteroides,815,genus
GTFTELAR,816,Bacteroides,815,genus
LDQSSTYQALQQLQMFMEYFPNSTK,816,Bacteroides,815,genus
LNNQLQVLQK,816,Bacteroides,815,genus
LSVAVADLFKPGDGVTLTPK,816,Bacteroides,815,genus
NGQNLPMPHFGNNFALEAQQVLYAGGALNSSLTLAELGQQMAALDWQK,816,Bacteroides,815,genus
QEAQDMLFALQDK,816,Bacteroides,815,genus
SMLDMEGYWK,816,Bacteroides,815,genus
VVNPVNYYFMDLSAEDYDR,816,Bacteroides,815,genus
AENAFLPR,817,Bacteroides fragilis,816,species
NGEYLPSFLSLDK,817,Bacteroides fragilis,816,species
LVLDHGFGYQTVYAHLR,820,Bacteroides uniformis,816,species
SLNFPEETLFFALTTK,820,Bacteroides uniformis,816,species
VGNVPATLDWLLTDSR,820,Bacteroides uniformis,816,species
YLADLYAR,820,Bacteroides uniformis,816,species
AAAVVLGHTDESVLQEYVADVLVGK,821,Bacteroides vulgatus,816,species
NLLETGNMGR,976,Bacteroidetes,68336,phylum
AEELLGAVENK,1263,Ruminococcus,541000,genus
AVSLAQSHR,1263,Ruminococcus,541000,genus
GTGLTEAANK,1263,Ruminococcus,541000,genus
LTGVVPEEQK,1263,Ruminococcus,541000,genus
VTPVHEFCDK,1263,Ruminococcus,541000,genus
FLLTGYYLDLYK,171549,Bacteroidales,200643,order
LTNEVVAMK,171549,Bacteroidales,200643,order
STGPHLHYEVHVK,171549,Bacteroidales,200643,order
FDSDLFVSK,186802,Clostridiales,186801,order
LLEVLGHK,186802,Clostridiales,186801,order
VDLLSLVK,186802,Clostridiales,186801,order
VMVELTDYGDAR,186802,Clostridiales,186801,order
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9049) by @pdawyndt on Wed Apr 30 2014 at 09:49._

**Comment by pdawyndt** [comment]
another issue

```
$ time fasta2prot < patient_TS19_CDS | head -n5000 | prot2pept | peptfilter | sort | uniq | unipept pept2lca -e | wc -l
API endpoint gave an error, exiting.
2694

real    0m0.843s
user    0m0.752s
sys     0m0.032s
$ time fasta2prot < patient_TS19_CDS | head -n10000 | prot2pept | peptfilter | sort | uniq | unipept pept2lca -e | wc -l
Exception IOError: IOError(32, 'Broken pipe') in <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'> ignored
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9050) by @pdawyndt on Wed Apr 30 2014 at 09:51._

**Comment by bmesuere** [comment]
source of error:

```
ArgumentError (comparison of NilClass with 51669 failed):
  app/controllers/api/api_controller.rb:67:in `sort'
  app/controllers/api/api_controller.rb:67:in `lca'
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9051) by @bmesuere on Wed Apr 30 2014 at 10:05._

**Comment by bmesuere** [comment]
This should now be fixed. I've pushed unipept 0.2.10 which should also exit more cleanly. 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/260#issuecomment-9116) by ghost on Fri May 02 2014 at 11:47._
