### ISSUE TITLE
unipept pept2prot should mention some additional information

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#264]
the output of the `unipept pept2prot` command should at least contain the description field of the protein record and the taxon id, and later should be expanded with functional information about the protein; see what information is currently available in the database; without having the taxon id of the protein records, it is now impossible to
rewrite the command

```
$ ... | unipept pept2taxa | ...
```

manually as

```
# filter third field as taxon id
$ ... | unipept pept2prot | awk -F, '{print $3}'  | ...
```

See for example the information shown in the [Uniprot tables](http://www.uniprot.org/uniprot/?query=mouse&sort=score) that list matching proteins:
- entry (accession number)
- entry name
- protein names
- gene names
- organism
- length

_[Original issue](https://github.ugent.be/unipept/unipept/issues/264) by @pdawyndt on Fri May 02 2014 at 20:50._
_Closed by an unknown user on Sun May 11 2014 at 13:40._

**Comment by pdawyndt** [comment]
I guess the output of the `unipept pept2prot` command should be the same as the default output of the `uniprot` command, except for the protein sequence itself.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9194) by @pdawyndt on Mon May 05 2014 at 09:24._

**Comment by bmesuere** [comment]
@pdawyndt I don't understand what you mean by your last comment. `uniprot` will only output the protein sequence found on the uniprot server?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9197) by ghost on Mon May 05 2014 at 09:31._

**Comment by pdawyndt** [comment]
`@tvwillem`: OK, my mistake then; I thought the `uniprot` command also had the option to show additional information about the protein sequence in CSV format.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9198) by @pdawyndt on Mon May 05 2014 at 09:37._

**Comment by pdawyndt** [comment]
`@tvwillem` : suggestion: by default, only show those information fields that are found in the uniprot table itself, i.e. the ones that can be fetched with no time penalty (uniprot accession number, taxon_id, ...); additional information that requires extra joins (taxon-name, cross-references) can be included as information fields triggered by an extra option.

I would recommend using the `-a` option (all information fields) for that (if not taken already), which has the same result as the `-l` option (lineage) for other commands. To be consistent, I would then also recommand to replace the `-l` option everywhere for the `-a` option. The `-s` option (select) can then also be used to select specific information fields (consistent with same option for other commands).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9246) by @pdawyndt on Tue May 06 2014 at 09:54._

**Comment by bmesuere** [comment]
The default is now fast again.

However, would it be OK to display go and ec references like this:
sequence, accession_number, taxon_id, taxon_name, list of references

or should the above line be repeated for each reference?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9247) by ghost on Tue May 06 2014 at 11:13._

**Comment by bmesuere** [comment]
A list of references (space separated?) is ok. I would make a separate column in the output for each type of reference:
sequence, accession_number, taxon_id, taxon_name, list of ec numbers, list of go terms


_[Original comment](https://github.ugent.be/unipept/unipept/issues/264#issuecomment-9252) by @bmesuere on Tue May 06 2014 at 13:29._
