### ISSUE TITLE
removal genomes both from local store and selection

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#271]
If one or more genomes are removed from the local store, they should also be removed from the list of selected genomes, and thus also from the analysis results. Should users get a warning that the latter will happen?

_[Original issue](https://github.ugent.be/unipept/unipept/issues/271) by @pdawyndt on Mon May 05 2014 at 08:33._
_Closed by @bmesuere on Mon May 05 2014 at 23:48._

**Comment by bmesuere** [comment]
Removing a genome from my genomes shouldn't remove it from the selected genomes.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/271#issuecomment-9243) by @bmesuere on Mon May 05 2014 at 23:48._
