### ISSUE TITLE
suggestions for small textual improvements

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#274]
## Peptidome analysis

The (tryptic) peptidome is the complete set of (tryptic) peptides encoded in the genome of an organism. Unipept provides fast and flexible analysis tools for identifying the unique peptidome of a given taxon and clustering whole-genomes based on their peptidome content.

## Unique peptide finder

Computes the unique peptidome for a selected set of RefSeq whole-genome sequences. Unique tryptic peptides are found in all selected genomes and in none of the Uniprot records belonging to taxa outside those of the selected genomes, making these peptides taxon-specific. Unique peptide sets can be downloaded and used in targeted proteomics experiments.

Incremental unions and intersections are computed for the peptidomes of all selected whole-genome sequences. The size of the incremental unions (pan peptidome) is shown in blue and the size of the incremental intersections (core peptidome) in orange. The size of the core peptidome subset that is unique to the lowest common ancestor (LCA) of the selected whole-genome sequences is shown in green. The size of the individual peptidomes &mdash; expressed as the total number of tryptic peptides &mdash; is shown in grey. Individual data sets can be shown/hidden by clicking their name in the graph legend.
1. Select peptidomes

All peptidomes derived from whole-genome RefSeq sequences assigned to a given species can be added to the selection, by picking the species from the drop-down list and clicking the 'Add species' button. Alternatively, individual peptidomes or all peptidomes belonging to a given taxon can be dragged from the tree (left) and dropped onto the selection (right). The selected set of peptidomes can be cleared or peptidomes can be removed from it individually.

Selection of a peptidome requires a server round-trip to download the set of peptides. The <symbol> symbol marks selected peptidomes whose set of peptides has not yet been downloaded.
1. Reorder peptidomes

Drag-and-drop selected peptidomes on the graph or the list to reorder them manually. Reorder all selected peptidomes by choosing the appropriate sort algorithm. The <symbol> symbol marks selected peptidomes whose graph values are currently being recomputed.
1. Download results

Download a list of peptides from the core peptidome that are unique to the lowest common ancestor (LCA) of the selected whole-genome sequences, by clicking the rightmost data point in the graph. Use the 'Download peptides' button from the popup menu and select 'Unique peptides'. Download the graph in PNG or SVG format, or as a Microsoft Excel-compatible CSV file.

## Peptidome clustering

Computes UPGMA clustering of a selected set of RefSeq whole-genome sequences based on their peptidome content. Pairwise similarities are computed as the fraction of the size of the intersection over the size of the union of both peptidomes.
1. Select peptidomes

All peptidomes derived from whole-genome RefSeq sequences assigned to a given species can be added to the selection, by picking the species from the drop-down list and clicking the 'Add species' button. Alternatively, individual peptidomes or all peptidomes belonging to a given taxon can be dragged from the tree (left) and dropped onto the selection (right). The selected set of peptidomes can be cleared or peptidomes can be removed from it individually.

Selection of a peptidome requires a server round-trip to download the set of peptides. The <symbol> symbol marks selected peptidomes whose set of peptides has not yet been downloaded.
1. Cluster peptidomes

The pairwise similarity matrix is automatically updated as peptidomes are added to or removed from the selection. Click the burred phylogenetic tree next to the similarity matrix to compute an UPGMA tree for all selected peptidomes. The list of selected peptidomes can be reordered according to the cluster order. The clustering can be undone, reinstating the order in which the selected peptidomes are listed onto the similarity matrix.
1. Download results

Click the 'Download data' button in the top-right corner to download the similarity matrix as a Microsoft Excel-compatible CSV file or to download UPGMA tree in Newick format. Click the 'Save image' button in the top-right corner to download the graph in PNG or SVG format.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/274) by @pdawyndt on Mon May 05 2014 at 21:55._
_Closed by @bmesuere on Sun May 11 2014 at 18:34._

**Comment by bmesuere** [comment]
Proposal for text in the selection panel + find a way to show these:
- left, first selection option: All peptidomes derived from whole-genome RefSeq sequences assigned to a given species can be added to the selection, by picking the species from the drop-down list and clicking the 'Add species' button.
- left: second selection option: Individual peptidomes or all peptidomes derived from whole-genome RefSeq sequences belonging to a given taxon can be dragged from the taxonomic tree (below) and dropped onto the selection (right). Use the edit box to filter the taxonomic tree.
- right (reodering): Drag-and-drop selected peptidomes on the graph (above) or the list to reorder them manually. Reorder all selected peptidomes by choosing the appropriate sort algorithm. The symbol marks selected peptidomes whose graph values are currently being recomputed.
- right (remark on order in list vs cluster order): Remark: The order in which the selected peptidomes are listed in the table below does not correspond to the order in which they are displayed in the similarity matrix above.
  right (deletion): The selected set of peptidomes can be cleared or peptidomes can be removed from it individually.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/274#issuecomment-9332) by @bmesuere on Wed May 07 2014 at 20:34._

**Comment by bmesuere** [comment]
The suggestions are great for a long-form manual or academic paper type of text, but for help/tooltips on a website a more concise form is preferred. Nevertheless, all suggestions were used as inspiration.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/274#issuecomment-9474) by @bmesuere on Sun May 11 2014 at 18:34._
