### ISSUE TITLE
suggested improvements for uniprot command

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#277]
- [x] `uniprot` command can be passed a list of Uniprot accession numbers as arguments; allow that uniprot command is read without arguments, in which case the list of Uniprot accession numbers is read from stdin (each accession number on a separate line; this would allow to write `... | xargs uniprot | ...` simply as `... | uniprot | ...`
- [x] uniprot command should either output some information fields (conform output of `pept2prot` subcommand of `unipept` with the `-a` option), the protein sequence itself, or both
- [x] add option to modify output format: fasta, csv (in both cases the accession numbers could then be part of the output)(see comment below)
- [x] no help information is currently displayed for the `uniprot command`
- [x] catch error if user interrupts execution midway (`^C`)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/277) by @pdawyndt on Tue May 06 2014 at 19:41._
_Closed by @bmesuere on Sat Aug 16 2014 at 14:59._

**Comment by pdawyndt** [comment]
Uniprot records can be downloaded in different formats using Uniprot web services. Here are some URL templates to download individual Uniprot records (exemplified for the Uniprot record with accession number `I8YV13`)
- TEXT: http://www.uniprot.org/uniprot/I8YV13.txt
- XML: http://www.uniprot.org/uniprot/I8YV13.xml
- RDF: http://www.uniprot.org/uniprot/I8YV13.rdf
- GFF: http://www.uniprot.org/uniprot/I8YV13.gff
- FASTA: http://www.uniprot.org/uniprot/I8YV13.fasta (may be a better option than reconstructing the FASTA file from the Unipept database)

we could add PLAIN as the default output format (protein sequences only, one sequence per line)

I guess Uniprot also provides webservices to download a multifasta file for multiple accession numbers at once


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9275) by @pdawyndt on Tue May 06 2014 at 19:43._

**Comment by pdawyndt** [comment]
question: does the `uniprot` command download sequences from Uniprot or from Unipept?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9280) by @pdawyndt on Tue May 06 2014 at 20:18._

**Comment by pdawyndt** [comment]
`@tvwillem` `-a` option of  `uniprot` command causes all output to be hidden; by default only the protein sequence should be shown (this is output in CSV-format, with a single column `protein`); additional information fields should be shown in case the `-a` or `-s` options are used, in analogy to the `unipept` command; the main difference between both commands is that the `unipept` command extracts its information from the Unipept database, whereas the `uniprot` command extracts its information from the Uniprot database. Here's an example use case

```
unipept pept2prot -e ENFVYIAK -s uniprot_id | uniprot -s uniprot_id -s protein | ...
uniprot_id,uniprot_sequence
P42654,mastkdrENFVYIAKlaeqaeryeemvdsmknvanldveltieernllsvgyknvigarr...
Q96453,mtaskdrENFVYIAKlaeqaeryeemvesmknvanldveltveernllsvgyknvigarr...
C6TH93,maaskdrENFVYIAKlaeqaeryeemvesmknvanldveltveerkkgvaildfilrlga...
C6TM63,maaskdrENFVYIAKlaeqaerfeemvesmknvanldveltveernllsvgyknvigarr...
M5WGY1,mgfaterENFVYLAKlseqaerydemvdamkkvanldveltveernllsvgyknvvgsrr...
I1LUM3,maaskdrENFVYIAKlaeqaeryeemvesmknvanldveltveernllsvgyknvigarr...
F6H2P0,marENFVYIAKlaeqaerydemvdamkkvakldvdltveernllsvgyknvigarraswr...
E1U3Z1,masskdrENFVYIAKlaeqaeryeemvdsmksvanldveltveernllsvgyknvigarr...
I3SLC5,mastkerENFVYIAKlaeqaeryeemveamknvakldveltveernllsvgyknvvgahr...
M0TAI1,masqkerENFVYIAKlaeqaerydemvdamkkvakldveltveernllsvgyknvvgarr...
I1M3M0,mtaskdrENFVYIAKlaeqaeryeemvesmknvanldveltveernllsvgyknvigarr...
G7LIR4,mastkerENFVYIAKlaeqaeryeemveamknvakldveltveernllsvgyknvvgahr...
M0TY03,masqkerENFVYIAKlaeqaerydemvdamkkvakldveltveernllsvgyknvvgarr...
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9904) by @pdawyndt on Sat May 24 2014 at 15:02._

**Comment by bmesuere** [comment]
@pdawyndt sidenote: you should try  `$ unipept pept2prot -e ENFVYIAK -s uniprot_id | uniprot --fasta`
which provides an alternative to your suggestion


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9905) by ghost on Sat May 24 2014 at 15:07._

**Comment by pdawyndt** [comment]
`@tvwillem` good suggestion; I'll put your suggestion in the case studies of your thesis; however, I think it is important that we keep the `unipept` and `uniprot` commands as orthogonal as possible

I don't see any documentation of the `uniprot` command when using the `-h` option, but I want to comment on the use of the `--fasta` option too; again in analogy to the `unipept` command, I would give the `uniprot` command an option `-f` followed by the format; the default format should be `csv` (orthogonal to `unipept` command) with other options as described above: `fasta`, `xml`, `text`, `rdf`, `gff`


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9906) by @pdawyndt on Sat May 24 2014 at 16:08._

**Comment by bmesuere** [comment]
@pdawyndt I completely agree. The current implementation of uniprot simply doesn't use the same argument and option parsing library (which also generates the help). The --fasta was a quick stop-gap solution which also helped with the testing of the fasta parsing of peptfilter, prot2pept and unipept.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-9907) by ghost on Sat May 24 2014 at 16:20._

**Comment by bmesuere** [comment]
`@tvwillem` @pdawyndt What needs to be done to close this issue?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-10521) by @bmesuere on Fri Aug 15 2014 at 14:21._

**Comment by bmesuere** [comment]
- The issue with the uniprot command is fixed in https://github.ugent.be/bmesuere/unipept-cli/commit/013ee1bc33ff8f61867fa531f5f76c58a3bad4a9
- I created bmesuere/unipept-cli#7 for the feature request regarding uniprot output formats


_[Original comment](https://github.ugent.be/unipept/unipept/issues/277#issuecomment-10526) by @bmesuere on Sat Aug 16 2014 at 14:59._
