### ISSUE TITLE
e-mail error reports

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#283]
_[Original issue](https://github.ugent.be/unipept/unipept/issues/283) by @bmesuere on Wed May 07 2014 at 15:35._
_Closed by @bmesuere on Tue May 27 2014 at 19:40._

**Comment by bmesuere** [comment]
Use the [custom notifier](https://github.com/smartinez87/exception_notification/blob/master/README.md#custom-notifier) to log to a file, and send hourly emails with a cron job/resque/rake/... to prevent spam


_[Original comment](https://github.ugent.be/unipept/unipept/issues/283#issuecomment-9648) by @bmesuere on Wed May 14 2014 at 11:36._

**Comment by pdawyndt** [comment]
In this particular case, not API error should follow in case a taxon ID is not found by the `taxa2lca` subcommand. It simply should report no output for that taxon ID. Same procedure is followed by the `pept2...` subcommands, that simply output no information on stdout for peptides coming from stdin that are not matched in the Unipept database.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/283#issuecomment-9652) by @pdawyndt on Wed May 14 2014 at 12:14._

**Comment by bmesuere** [comment]
fixed in 1650c53b4dc6e07aa468d6f6aa21a99332cede0a


_[Original comment](https://github.ugent.be/unipept/unipept/issues/283#issuecomment-9943) by @bmesuere on Tue May 27 2014 at 19:40._
