### ISSUE TITLE
better abbreviations

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#289]
- don't abbreviate single word names
- only abbreviate "my genomes" if length > 30
- pathovar -> pv.
- serovar -> sv.
- species -> sp.
- genomovar -> gv.
- subspecies -> subsp.
- strain -> str.
- Candidatus -> Ca.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/289) by @bmesuere on Wed May 07 2014 at 20:51._
_Closed by @bmesuere on Sun May 11 2014 at 21:51._

**Comment by pdawyndt** [comment]
Here are some other ideas to clean the labels, which I played with in the Python implementation I've written last week to test different aggregation scenarios for the metagenomics datasets: 
- only abbreviate if the first word starts with a capital and is followed by a series of lowercase letters
- only abbreviate first word if it corresponds to the name of the parent node in the taxonomy (might solve some issues with names of viruses)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/289#issuecomment-9479) by @pdawyndt on Sun May 11 2014 at 21:17._

**Comment by bmesuere** [comment]
Manually went through all names and abbreviations and added 1 more rule. Everything seems ok now. Since data about parent nodes is not available, the second option would impose a performance hit.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/289#issuecomment-9482) by @bmesuere on Sun May 11 2014 at 21:51._

**Comment by pdawyndt** [comment]
@bmesuere : can you check whether the name ´Candidatus´ is abbreviated as `C.`. According to [Wikipedia](http://en.wikipedia.org/wiki/Candidatus) the correct abbreviation is `Ca.`.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/289#issuecomment-9636) by @pdawyndt on Tue May 13 2014 at 21:15._

**Comment by bmesuere** [comment]
@pdawyndt fixed


_[Original comment](https://github.ugent.be/unipept/unipept/issues/289#issuecomment-9637) by @bmesuere on Tue May 13 2014 at 21:26._
