### ISSUE TITLE
replace root by organism in taxonomic hierarchy

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#29]
the term root as the root of the NCBI taxonomy is not very informative if later on also other ontologies like the gene ontology will be integrated in Unipept. Therefore, I suggest to start using the generic term organism as the name for the top-level node in the NCBI taxonomy (unless this name already has another specific meaning in the NCBI taxonomy).

_[Original issue](https://github.ugent.be/unipept/unipept/issues/29) by @pdawyndt on Thu May 17 2012 at 11:14._
_Closed by @bmesuere on Tue May 29 2012 at 14:56._

**Comment by bmesuere** [comment]
NCBI describes this level as "the top level of the taxonomy database" in full text and as "root" in their lineage (e.g. http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=2&lvl=3&lin=f&keep=1&srchmode=1&unlock )


_[Original comment](https://github.ugent.be/unipept/unipept/issues/29#issuecomment-10) by @bmesuere on Thu May 17 2012 at 19:54._
