### ISSUE TITLE
taxa2lca is vulnerable to different order of listed input taxon IDs

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#296]
`taxa2lca` subcommand should be insensitive to the order in which the taxon IDs are listed in stdin; however, this is not the case in the following example

```
$ echo "2\n131567\n" | unipept taxa2lca
taxon_id,taxon_name,taxon_parent_id,taxon_rank
2,Bacteria,131567,superkingdom
$ echo "131567\n2\n" | unipept taxa2lca
taxon_id,taxon_name,taxon_parent_id,taxon_rank
1,root,1,no rank
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/296) by @pdawyndt on Thu May 08 2014 at 20:49._
_Closed by @bmesuere on Fri May 09 2014 at 15:47._

**Comment by bmesuere** [comment]
On my machine this produces the same output (root). @pdawyndt If you provide an exact timestamp you ran these tests, I can maybe pinpoint the error with the logs on scruffy. 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/296#issuecomment-9404) by ghost on Fri May 09 2014 at 15:00._

**Comment by bmesuere** [comment]
The issue here has to do echo itself. Using echo -e seems to solve this.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/296#issuecomment-9409) by ghost on Fri May 09 2014 at 15:45._

**Comment by pdawyndt** [comment]
@bmesuere `@tvwillem` : sure, my mistake; however, I still think it's less correct to give root as LCA here, but I'll discuss this in another existing issue that deals with possible scenarios for aggregation over taxonomic hierarchies.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/296#issuecomment-9423) by @pdawyndt on Sat May 10 2014 at 09:32._
