### ISSUE TITLE
reoder lineage fields

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#298]
Now the lineage fields are reported in an order where first the names of all ranks are listed, following by the taxon IDs of all ranks. It would feel more natural to list them in alternating order, as a kind of (taxon_id, name) pairs. Actually, they are (taxon_id, name, rank) triplets, if the field header is taken into account.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/298) by @pdawyndt on Thu May 08 2014 at 21:04._
_Closed by an unknown user on Mon May 12 2014 at 08:28._

**Comment by pdawyndt** [comment]
I know this is a detail, but it would feel more natural to me to have the columns listed as (taxon_id, name) pairs. Now they are listed as (name, taxon_id) pairs.

`@tvwillem` : do you intend to keep the `-l` option to show the complete lineage for each taxon ID in the output, or have we agreed on replacing it by the `-a` option for consistency with other command in the Unipept command line suit. Maybe I'm mistaken, and we need both the `-a` and `-l` options


_[Original comment](https://github.ugent.be/unipept/unipept/issues/298#issuecomment-9478) by @pdawyndt on Sun May 11 2014 at 21:14._

**Comment by bmesuere** [comment]
@pdawyndt I've reorderd them as you suggested. 

I've replaced all -l options with -a (which will be released as unipept 0.4.0 as it is not backwards compatible)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/298#issuecomment-9486) by ghost on Mon May 12 2014 at 08:28._
