### ISSUE TITLE
CSV output inconsistency

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#300]
I have no idea what is the common representation of _empty fields_ in CSV output, but in the current implementation of the command line tools they are sometimes show as empty strings (in between successive commas) and sometimes as a pair of double quotes (quoted empty strings in between successive commas). See the example below, showing the inconsistency

```
$ fasta2prot < patient_TS19_CDS | sed -ne '27{p;q}' | prot2pept | peptfilter | unipept pept2lca -el
sequence,taxon_id,taxon_name,taxon_parent_id,taxon_rank,superkingdom_name,kingdom_name,subkingdom_name,superphylum_name,phylum_name,subphylum_name,superclass_name,class__name,subclass_name,infraclass_name,superorder_name,order_name,suborder_name,infraorder_name,parvorder_name,superfamily_name,family_name,subfamily_name,tribe_name,subtribe_name,genus_name,subgenus_name,species_group_name,species_subgroup_name,species_name,subspecies_name,varietas_name,forma_name,superkingdom_id,kingdom_id,subkingdom_id,superphylum_id,phylum_id,subphylum_id,superclass_id,class__id,subclass_id,infraclass_id,superorder_id,order_id,suborder_id,infraorder_id,parvorder_id,superfamily_id,family_id,subfamily_id,tribe_id,subtribe_id,genus_id,subgenus_id,species_group_id,species_subgroup_id,species_id,subspecies_id,varietas_id,forma_id
INYDFAGK,171549,Bacteroidales,200643,order,Bacteria,"","",Bacteroidetes/Chlorobi group,Bacteroidetes,"","",Bacteroidia,"","","",Bacteroidales,"","","","","","","","","","","","","","","","",2,,,68336,976,,,200643,,,,171549,,,,,,,,,,,,,,,,
YLLEANIR,976,Bacteroidetes,68336,phylum,Bacteria,"","",Bacteroidetes/Chlorobi group,Bacteroidetes,"","","","","","","","","","","","","","","","","","","","","","","",2,,,68336,976,,,,,,,,,,,,,,,,,,,,,,,
ADASSR,1,root,1,no rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
FAEGHR,1,root,1,no rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
VHGASAR,95486,Burkholderia cenocepacia,87882,species,Bacteria,"","","",Proteobacteria,"","",Betaproteobacteria,"","","",Burkholderiales,"","","","",Burkholderiaceae,"","","",Burkholderia,"",Burkholderia cepacia complex,"",Burkholderia cenocepacia,"","","",2,,,,1224,,,28216,,,,80840,,,,,119060,,,,32008,,87882,,95486,,,
NEGIGK,1,root,1,no rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/300) by @pdawyndt on Sat May 10 2014 at 10:30._
_Closed by an unknown user on Mon May 12 2014 at 09:09._

**Comment by bmesuere** [comment]
It seems like empty strings are shown as "", and empty numbers as nothing.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/300#issuecomment-9430) by @bmesuere on Sat May 10 2014 at 10:48._

**Comment by pdawyndt** [comment]
That's what I thought at first too, but look at the last CSV record in the above example. The first half of the empty fields are missing names, and they are shown without double quotes. Also, I would have expected all strings to be enclosed in double quotes. My guess was that CSV common practice was to only quote field content in case it contains the delimiter character (in this case a comma). In that case, however, most of the fields should not use double quotes. But it's a detail anyway (problem with loosely defined formats).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/300#issuecomment-9431) by @pdawyndt on Sat May 10 2014 at 10:54._
