### ISSUE TITLE
add Unipept paper to metaproteomics page of wikipedia

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#301]
http://en.wikipedia.org/wiki/Metaproteomics

_[Original issue](https://github.ugent.be/unipept/unipept/issues/301) by @pdawyndt on Sat May 10 2014 at 14:55._
_Closed by @bmesuere on Sun Jan 24 2016 at 13:24._

**Comment by bmesuere** [comment]
I added a Unipept page: http://en.wikipedia.org/wiki/Unipept


_[Original comment](https://github.ugent.be/unipept/unipept/issues/301#issuecomment-19524) by @bmesuere on Mon Aug 24 2015 at 21:44._
