### ISSUE TITLE
database construction improvements

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#302]
possible construction speedups:
- for all tryptic peptides that do not contain any `I` or `L`, the same LCA will be found whether or not both amino acids are treated equal or different; therefore, there is no need to compute the LCAs for these tryptic peptides twice
- index size could be reduced as there is no need to store the I=L variant of peptides that do not contain I and L; however, this might seriously complicate queries as individual joins would be needed for peptides having or lacking I or L

possible service speedups:
- keep hierarchical data structure representing the Unipept Taxonomy in memory (server-side); maybe this even obsoletes the construction of a table containing the full lineages for all taxa; could also be used to browse the Unipept Taxonomy on the website

_[Original issue](https://github.ugent.be/unipept/unipept/issues/302) by @pdawyndt on Sat May 10 2014 at 15:05._
_Closed by @bmesuere on Sun Jan 24 2016 at 13:25._

**Comment by bmesuere** [comment]
this was fixed a long time ago


_[Original comment](https://github.ugent.be/unipept/unipept/issues/302#issuecomment-24353) by @bmesuere on Sun Jan 24 2016 at 13:25._
