### ISSUE TITLE
CSV field header: uniprot_id instead of uniprot_accession_number

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#303]
`@tvwillem`  @bmesuere For consistency with the field header `taxon_id` I would recommend to rename the CSV field header `uniprot_accession_number` as `uniprot_id`. I guess this could also imply that later on the corresponding database column headers and names returned in the output of the web services might need to be replaced.

I already made use of the name `unipept_id` in the text I'm currently compiling for Toon's thesis, in which I'm discussing some use cases of the Unipept command line as an illustration on how to use the tools and a kind of benchmark to prove how usefull the API is in practice.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/303) by @pdawyndt on Sat May 10 2014 at 19:05._
_Closed by an unknown user on Sun May 11 2014 at 13:09._

**Comment by bmesuere** [comment]
Fixed in bcc8f38


_[Original comment](https://github.ugent.be/unipept/unipept/issues/303#issuecomment-9468) by ghost on Sun May 11 2014 at 13:09._
