### ISSUE TITLE
numbers on top of scale partly hidden in full screen mode

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#309]
If I view the clustering in full screen mode, the numbers on top of the scale partly disappear at the top of the screen. If possible, the whole viewport should be lowered a little bit.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/309) by @pdawyndt on Sun May 11 2014 at 21:32._
_Closed by @pdawyndt on Sun May 11 2014 at 22:06._

**Comment by bmesuere** [comment]
How can I reproduce this problem? I tried in both Chrome and Firefox and everything seems to be ok. Is your zoom setting on 100%?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/309#issuecomment-9483) by @bmesuere on Sun May 11 2014 at 21:58._

**Comment by pdawyndt** [comment]
@bmesuere : I set the zoom level to 100%, and the problem has disappeard. Solves this issue.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/309#issuecomment-9484) by @pdawyndt on Sun May 11 2014 at 22:06._
