### ISSUE TITLE
Supply a docker image for the Unipept server

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#310]
After discussion with the HPC`@UGent` team, Bart came up with the idea of supplying the Unipept server as a virtual machine for local installation. I think this would be a great idea. To go even further, power users that run one or more instances of the Unipept server could also donate free CPU cycles to the community. This would require a scheduler that dispatches user request (which are already split in several blocks anyway) across the available Unipept servers. This could also be used as a load balancer if users run multiple private instances of the Unipept server. Probably there are already frameworks that can handle this kind of dispatching.

Perhaps the dispatcher than also would need to take into account the version numbers of the available Unipept instances, and clients could selectively target certain instances. In addition, some scenario could be tought over to automatically update Unipept servers if new versions of the database become available.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/310) by @pdawyndt on Sun May 11 2014 at 21:36._

**Comment by bmesuere** [comment]
[Docker](https://www.docker.io/) might be an option


_[Original comment](https://github.ugent.be/unipept/unipept/issues/310#issuecomment-9880) by @bmesuere on Fri May 23 2014 at 10:31._

**Comment by bmesuere** [comment]
Passenger provides base docker images for rails deployment. (as seen https://github.com/phusion/passenger-docker)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/310#issuecomment-9881) by ghost on Fri May 23 2014 at 10:32._

**Comment by pdawyndt** [comment]
see also:
- S. V. Angiuoli, M. Matalka, A. Gussman, K. Galens, M. Vangala, D. R. Riley, C. Arze, J. R. White, O. White, and W. F. Fricke. Clovr: a virtual machine for automated and portable sequence analysis from the desktop using cloud computing. BMC Bioinformatics, 12:356, 2011.
-  A. Wilke, J. Wilkening, E.M. Glass, N. Desai, and F. Meyer. An experience report: porting the mg-rast rapid metagenomics analysis pipeline to the cloud. Concurrency and Computation: Practice and Experience, 23(17):22502257, 2011.
-  J. Wilkening, A. Wilke, Narayan Desai, and Folker Meyer. Using clouds for metagenomics: A case study. In
  IEEE Cluster 2009 , 2009.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/310#issuecomment-9975) by @pdawyndt on Sun Jun 01 2014 at 12:30._
