### ISSUE TITLE
performance penalty with successive calls of prot2pept

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#320]
`@tvwillem` When I run the `prot2pept` command in the following scenario
- read all proteins from a sample from stdin at once
- break all of them up into peptides doing a single call of `prot2pept`

This takes only a few seconds. However, if I implement it in a loop, where there's a single call to `prot2pept` per protein, this gives a serious performance penalty. Here's the script that shows the problem (it reads a fasta file containing proteins as input).

```
#!/bin/bash

# process command line arguments
sample_prot=$(readlink -f "$1")
sample_prot2pept="${sample_prot}.prot2pept"
sample_metapept="${sample_prot}.metapept"

# step1: parse fasta file and break each protein sequence into its tryptic peptides
#        this step is needed to be able to aggregate the tryptic peptides back to the
#        protein or DNA read level
cat "${sample_prot}" | while read line
do
  if [ "${line:0:1}" = ">" ]
  then
    if [ -n "${sequence}" ]
    then
      echo "${header}"
      echo "${sequence}" | prot2pept | peptfilter | tail -n +2 | grep -v '^$'
    fi
    header="${line}"
    sequence=""
  else
    sequence="${sequence}${line}"
  fi
done > "${sample_prot2pept}"
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/320) by @pdawyndt on Wed May 14 2014 at 13:11._
_Closed by an unknown user on Mon May 19 2014 at 15:26._

**Comment by bmesuere** [comment]
unipept 0.5.0 now has preliminary support for FASTA input.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/320#issuecomment-9846) by ghost on Mon May 19 2014 at 15:26._

**Comment by pdawyndt** [comment]
`@tvwillem` This would ease things a lot for client-side scripts. Great addition. I'll test it later on. Now I have to rush a bit doing some more data processing (I have some news for next Wednesday; check your email in a few minutes).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/320#issuecomment-9852) by @pdawyndt on Mon May 19 2014 at 17:45._
