### ISSUE TITLE
unipept.log file

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#323]
I got this message in the `unipept.log` file in my home folder when processing 12 samples of an EBI shotgun metagenomics project at once.

``` htlm
<h1>This website is under heavy load</h1><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
```

This is indeed a nice feature, but some minor remarks:
- the command line tools each time overwrite the same file; is this what we want, or do we want log messages with a given timestamp
- shouldn't the file be a hidden file, so `.unipept.log` ?

_[Original issue](https://github.ugent.be/unipept/unipept/issues/323) by @pdawyndt on Wed May 14 2014 at 20:44._
_Closed by an unknown user on Mon May 19 2014 at 10:46._

**Comment by bmesuere** [comment]
(That message isn't something we added, but the webserver (passenger) complaining there are too many (100) open connections.)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/323#issuecomment-9671) by @bmesuere on Wed May 14 2014 at 20:59._
