### ISSUE TITLE
why don't we find more viruses?

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#324]
An open question: could it be that the large pool of peptides that has 'root' as its lowest common ancestor (LCA) is somewhat biased? here's a tought experiment: if viruses affect humans, animals, bacteria (phages), it could well be that the proteins of a given virus are annotated both as coming from the virus and from their host; the latter are actual false taxonomic assignments, but as soon as a peptide is found both in a virus and one of its hosts, the peptide becomes marked as 'root'. We could do a screening to see if this problem can be remedied. Can we spot these wrong annotations? Correct them automatically, or take them into account during the LCA computation?

**see also**
- #329

**literature**
- [Dulith BE (2014). Virus discovery by metagenomics: the (im)possibilities. Frontiers in Microbiology](http://www.frontiersin.org/virology/researchtopics/virus_discovery_by_metagenomic/2708)
- [virome](http://standardsingenomics.org/index.php/sigen/article/view/sigs.2945051)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/324) by @pdawyndt on Thu May 15 2014 at 00:38._

**Comment by bmesuere** [comment]
Isn't this mostly due to the small size of viral genomes? If the genome is 500 (?) times smaller, aren't the odds to pick up viral peptides equally reduced?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/324#issuecomment-10027) by @bmesuere on Mon Jun 09 2014 at 22:03._
