### ISSUE TITLE
improved LCA computation?

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#325]
Think whether or not it would give better performance if instead of computing the LCA using the following loop

``` python
proteins, peptides = set(), set()
for protein in uniprot.proteins:
    proteins.add(protein)
    for peptide in protein.digest():
        peptide = peptides.proteins.add(protein)

for peptide in peptides:
    taxa = {protein.taxon.id for protein in peptide.proteins}
    peptide.lca = LCA(taxa)
```

it would be better to implement it in the following (equivalent) way

``` python
proteins, peptides = set(), set()
for protein in uniprot.proteins:
    proteins.add(protein)
    for peptide in protein.digest():
        peptide = peptides.add(peptide)
        if  peptide.taxontree is not None:    # number of children of root < 2
            peptide.taxontree.add(protein.taxon.id)
        else:
            peptide.lca = 'root'
            peptide.taxontree = None
for peptide in peptides:
    if peptide.lca is None:
        peptide.lca = LCA(peptide.taxontree)
```

peptides whose taxontree already give a root LCA might be skipped in the process, since adding yet another taxon to the tree will not change the outcome; this procedure iterates over the peptides of the proteins only once, but it requires to lookup the peptides and map them to there taxontree, which needs to be stored in addition (in memory or in the database); however, large taxon trees have higher change to become root, in which case the (partial) tree can immediately be removed and the LCA can already be set instead; as soon as the LCA is set, there's no more need for the taxon tree

_[Original issue](https://github.ugent.be/unipept/unipept/issues/325) by @pdawyndt on Thu May 15 2014 at 00:59._
_Closed by @bmesuere on Mon Aug 04 2014 at 14:04._

**Comment by bmesuere** [comment]
New Java LCA implementation is fast enough.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/325#issuecomment-10355) by @bmesuere on Mon Aug 04 2014 at 14:04._
