### ISSUE TITLE
pooling of results

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#331]
The current implementation of the Unipept Shotgun Metagenomics Pipeline uses two-level pooling:
- all tryptic peptides from a sample are pooled into the sample metapeptidome (uniq > set)
- all tryptic peptides from all samples of a project are pooled into the project metapeptidome (uniq > set)

This gives a serious reduction in the number of peptides for which the lowest common ancestor has to be looked up by the `unipept pept2lca` command in the current implementation. However, once the `unipept` commands accept FASTA records as input and produce FASTA records as output, this pooling could be done by the `unipept` command itself. As this may come with some memory overhead, this could be made an optional feature (or at least one that could be turned off).

Here's an illustration of the first level of pooling (sample level).

![usmp_sample_pooling](https://github.ugent.be/github-enterprise-assets/0000/0006/0000/0170/271df7de-de62-11e3-8888-236fe9d59e0d.png)

Here's an illustration of the second level of pooling (project level).

![usmp_project_pooling](https://github.ugent.be/github-enterprise-assets/0000/0006/0000/0171/2ca8a208-de62-11e3-920d-5519c6884220.png)

`@tvwillem` I don't expect you to implement this feature in the framework of your thesis (give priority to see whether you could handle FASTA-in FASTA-out), but give this a thought for your defense as future work

_[Original issue](https://github.ugent.be/unipept/unipept/issues/331) by @pdawyndt on Sun May 18 2014 at 09:59._
_Closed by @bmesuere on Mon Feb 01 2016 at 14:46._

**Comment by bmesuere** [comment]
Joining needs a sort and is many times slower than looking up the peptide multiple times using `pept2lca`.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/331#issuecomment-24507) by @bmesuere on Mon Feb 01 2016 at 14:46._
