### ISSUE TITLE
empty line appears in output

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#336]
`@tvwillem` Bart & I are checking the demo for tomorrow, and we now have an ugly empty line in the output of the unipept command. Could you see if this one can be removed.

```
$ unipept pept2prot ENFVYIAK

sequence,uniprot_id,taxon_id
ENFVYIAK,P42654,3906
ENFVYIAK,Q96453,3847
ENFVYIAK,C6TH93,3847
ENFVYIAK,C6TM63,3847
ENFVYIAK,I1LUM3,3847
ENFVYIAK,F6H2P0,29760
ENFVYIAK,E1U3Z1,3827
ENFVYIAK,I3SLC5,3880
ENFVYIAK,M0TAI1,214687
ENFVYIAK,I1M3M0,3847
ENFVYIAK,G7LIR4,3880
ENFVYIAK,M0TY03,214687
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/336) by @pdawyndt on Tue May 20 2014 at 17:16._
_Closed by an unknown user on Tue May 20 2014 at 17:31._

**Comment by bmesuere** [comment]
Fixed in unipept 0.5.4.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/336#issuecomment-9865) by ghost on Tue May 20 2014 at 17:31._
