### ISSUE TITLE
add option to enable miscleavage handling from CLI

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#337]
This would give the `unipept command` the same interface as the online version. 

_[Original issue](https://github.ugent.be/unipept/unipept/issues/337) by @pdawyndt on Tue May 20 2014 at 18:03._
_Closed by @bmesuere on Wed May 20 2015 at 18:51._

**Comment by bmesuere** [comment]
duplicate of unipept/unipept-cli#32


_[Original comment](https://github.ugent.be/unipept/unipept/issues/337#issuecomment-18123) by @bmesuere on Wed May 20 2015 at 18:51._
