### ISSUE TITLE
do we all have Daphnia in our gut?

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#339]
This morning at breakfast I recalled the _Daphnia_ story, so I quickly looked into the [data set of the lean and obese twins](https://www.ebi.ac.uk/metagenomics/project/SRP000319) (I now also have run the two larger samples in the projects). Here are just the counts of the number of peptides that have the genus _Daphnia_ (or one of its species) as their lowest common ancestor.

```
SRS000998:39
SRS000999:49
SRS001000:71
SRS001001:42
SRS001002:56
SRS001003:67
SRS001004:98
SRS001005:73
SRS001006:76
SRS001007:61
SRS001008:57
SRS001009:43
SRS001012:70
SRS001013:64
SRS001014:55
SRS001015:67
SRS009825:558
SRS009826:352
```

The list still uses the EBI sample numbers, to its not immediately clear which ones are from the lean and the obese persons. However, it's already clear that _Daphnia_ occurs in all their guts. Actually, in most cases, the lowest common ancestor is specific at the species level: _Daphnia pulex_. Here are number of _Daphnia pulex_ (peptides, not DNA reads/proteins)

```
SRS000998:39
SRS000999:46
SRS001000:70
SRS001001:42
SRS001002:55
SRS001003:64
SRS001004:98
SRS001005:71
SRS001006:76
SRS001007:60
SRS001008:57
SRS001009:42
SRS001012:70
SRS001013:64
SRS001014:55
SRS001015:66
SRS009825:543
SRS009826:348
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/339) by @pdawyndt on Thu May 22 2014 at 06:44._
_Closed by @bmesuere on Tue May 27 2014 at 17:21._

**Comment by pdawyndt** [comment]
I also checked the [data set of the breast/formula fed babies](https://www.ebi.ac.uk/metagenomics/project/ERP001038). Same story over there.

```
ERS075404:35
ERS075405:16
ERS075406:33
ERS075407:69
ERS075408:56
ERS075409:26
ERS075410:31
ERS075411:32
ERS075412:20
ERS075413:33
ERS075414:17
ERS075415:21
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/339#issuecomment-9870) by @pdawyndt on Thu May 22 2014 at 06:48._

**Comment by bmesuere** [comment]
@pdawyndt Can you easily extract a list of the respective proteins?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/339#issuecomment-9874) by @bmesuere on Thu May 22 2014 at 11:24._

**Comment by bmesuere** [comment]
@pdawyndt can this be closed?
If I remember well, we tried to blast some daphnia hits and didn't find any convincing evidence.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/339#issuecomment-9939) by @bmesuere on Tue May 27 2014 at 16:52._

**Comment by pdawyndt** [comment]
@bmesuere The BLAST hits indeed confirmed that the proteins were not Daphnia specific at first sight. This will be explored futher if we benchmark the metagenomics/metaproteomics analysis pipelines for the taxonomic accurracy and correctness on all RefSeq genomes (making a distinction between the ones that are in Unipept and the ones that are not).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/339#issuecomment-9942) by @pdawyndt on Tue May 27 2014 at 18:49._
