### ISSUE TITLE
optionally add LCA information to pept2prot

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#345]
request from Lennart Martens to have a single web service that does the prot2pept2lca join; this gives redundant information, but would be make things easier user-side; would be possible to do some pooling here

```
join -t, -11 -21 <(unipept pept2prot -ea ENFVYLAK | tail -n +2) <(unipept pept2lca -ea ENFVYLAK | tail -n +2)
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/345) by @pdawyndt on Fri May 23 2014 at 11:36._

**Comment by bmesuere** [comment]
I think it would make more sense to optionally (-a or new flag) include the lca information in `pept2prot`


_[Original comment](https://github.ugent.be/unipept/unipept/issues/345#issuecomment-9886) by @bmesuere on Fri May 23 2014 at 12:00._

**Comment by pdawyndt** [comment]
that could indeed be another option; I agree with this suggestion


_[Original comment](https://github.ugent.be/unipept/unipept/issues/345#issuecomment-9887) by @pdawyndt on Fri May 23 2014 at 12:05._
