### ISSUE TITLE
rename fields + change default and optional fields

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#348]
The following issues hold for all subcommands of the `unipept` command
- [x] rename information field `sequence` into information field `unipept_sequence` (in analogy to the information field `uniprot_sequence` of the `uniprot` command); this will allow to make distinction between both sequences in case they are shown in the same record (see request for `pept2prot2lca` command/web service #345); open for discussion: as an alternative, we could name the fields `peptide_sequence` and `protein_sequence` (or `peptide` and `sequence` for short) in order not to bind the names to any database

The following issues hold for the `pept2prot` subcommand of the `unipept` command
- [x] default information fields that are returned by `unipept pept2prot` are `unipept_sequence` and `uniprot_id`; the information field `taxon_id` already requires an additional database join
- [ ] information fields requested by the `unipept pept2prot` command should be passed to the `pept2prot` web service; the web service should only return the requested information fields, whereas now it might happen that some additional information fields are passed to the `unipept` command, which then applies additional filtering; if the web services only provided the requested information fields, this allows to reduce network bandwidth and smart implementations of the web services that only perform the database joins that are needed to provided the requested information (minimal information > fast; maximal information > slower)

The following issues hold for the `pept2taxa` subcommand of the `unipept` command
- [x] default information fields that are returned by `unipept pept2taxa` are `unipept_sequence` and `taxon_id`; the information fields `taxon_name`, `taxon_parent_id` and `taxon_rank` already require an additional database join
- [ ] information fields requested by the `unipept pept2taxa` command should be passed to the `pept2taxa` web service; the web service should only return the requested information fields, whereas now it might happen that some additional information fields are passed to the `unipept` command, which then applies additional filtering; if the web services only provided the requested information fields, this allows to reduce network bandwidth and smart implementations of the web services that only perform the database joins that are needed to provided the requested information (minimal information > fast; maximal information > slower)

The following issues hold for the `pept2lca` subcommand of the `unipept` command
- [x] default information fields that are returned by `unipept pept2lca` are `unipept_sequence` and `taxon_id`; the information fields `taxon_name`, `taxon_parent_id` and `taxon_rank` already require an additional database join
- [ ] information fields requested by the `unipept pept2lca` command should be passed to the `pept2lca` web service; the web service should only return the requested information fields, whereas now it might happen that some additional information fields are passed to the `unipept` command, which then applies additional filtering; if the web services only provided the requested information fields, this allows to reduce network bandwidth and smart implementations of the web services that only perform the database joins that are needed to provided the requested information (minimal information > fast; maximal information > slower)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/348) by @pdawyndt on Sat May 24 2014 at 15:54._
_Closed by @bmesuere on Wed May 20 2015 at 18:22._

**Comment by bmesuere** [comment]
> default information fields that are returned by unipept pept2prot are unipept_sequence and uniprot_id; the information field taxon_id already requires an additional database join

This isn't correct. Joining the sequences and peptides table gives you: `sequence`, `lca` (i.e. a taxonId) `lca_il`, `position` (the position of the peptide in the protein sequence) and the internal IDs of sequence, peptide en uniprot_entry. Nothing of these is really useful for the pept2prot command.

If you add the uniprot_entries table to the mix, you get the uniprot accession number, taxon_id associated with the entry, type (swissprot or embl) and the full protein sequence.

I think we should at least return the uniprot accession number, so returning the associated taxon_id isn't an extra cost. Returning the name of that taxon does require an extra query.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/348#issuecomment-9940) by @bmesuere on Tue May 27 2014 at 17:06._

**Comment by pdawyndt** [comment]
@bmesuere OK, so then the default return fields should be the peptide, the Uniprot accession number  and the NCBI Taxonomy taxon ID


_[Original comment](https://github.ugent.be/unipept/unipept/issues/348#issuecomment-9941) by @pdawyndt on Tue May 27 2014 at 18:45._

**Comment by bmesuere** [comment]
Will close this for now. When the API has support for selecting fields, the rest can be implemented.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/348#issuecomment-18115) by @bmesuere on Wed May 20 2015 at 18:22._
