### ISSUE TITLE
suggested reorganization of Unipept website

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#349]
**future naming of Unipept analysis pipelines**
- [x] _tryptic peptide analysis_ (new name of _single peptide analysis_): taxonomic and functional analysis of a single tryptic peptide
- [x] _metaproteomics analysis_ (new name of _multi-peptide analysis_): based on protein read analysis (metaproteomics data sets may contain miscleavages, which are protein reads)
- [ ] _protein read analysis_ (new feature): taxonomic and functional analysis of a protein read; protein is broken into individual tryptic peptides, peptides are analyzed individually, results are aggregated at protein read level (useful for both partial and complete proteins)
- [ ] _DNA read analysis_ (new feature): gene calling on DNA read (e.g. `FragGeneScan`), resulting proteins are broken into individual tryptic peptides, peptides are analyzed individually, results are aggregated at protein or DNA read level (usefull for anything in between short reads, contigs and complete genomes)
- [ ] _metagenomics analysis_ (new feature): based on DNA read analysis; due to sheer size of data sets, only provided through Unipept API; website only documents API and provides use case scenarios
- [ ] _peptidome analysis_: encompasses both _unique peptide finder_ and _peptidome-based whole-genome clustering_
- [ ] _Unipept API_: encompasses both web services and command line interface; website only documents API and provides use case scenarios
- [ ] _comparative meta-omics workbench_: create samples (list of taxonomic assignments from individual protein (metaproteomics) or DNA (metagenomics) reads) and projects (list of samples); data analysis and visualization tools for individual samples; data analysis and visualization tools for comparing samples in a project; documentation on how to dock sample and project analysis tools into external web pages

**suggestions for _tryptic peptide analysis_ results page**
- [x] rename title into _Analysis of tryptic peptide ENFVYIAK_ or simple _tryptic peptide ENFVYIAK_
- [ ] analysis results section should have three tabs
  - matching proteins (Uniprot; next two tabs depend on this result)
  - taxonomic analysis
  - functional analysis (for the moment this could be just a table of the EC numbers and GO terms from matching proteins)
- [ ] matching proteins tab should show a table with all the information on the matching Uniprot proteins that is available in Unipept and also have a button to blast the protein; table should show Uniprot Accession Number, which is linked to the corresponding Uniprot record
- [ ] taxonomic analysis tab should itself have another two tabs, one that shows the results in a tree and another that shows the results in tabular format; both table and tree should be linked to NCBI Taxonomy Database (and also Uniprot Taxonomy when this is available for graphical inspection)
  - both tree and table should indicate the number of matching proteins for each taxon, and link into these proteins similar to the way the results page of the _metaproteomics analysis_ links to the different peptides at a given taxonomic node
  - both tree and table should show a visual representation of the lowest common ancestor
  - lowest common ancestor information (choose _lowest common ancestor_ as header, not just _information_) should appear below the tree/table as it is derived from this information

This way of visualization is more in line with the order of the computations that are done: peptide > matching proteins > taxa > lowest common ancestor (or any other taxonomic aggregation)

**suggestions for _metaproteomics analysis_ results page**
- [x] add visual tree view with color coded nodes (representing counts/weights) as an alternative for the sunburst and treemap visualizations

_[Original issue](https://github.ugent.be/unipept/unipept/issues/349) by @pdawyndt on Sat May 24 2014 at 17:48._

**Comment by bmesuere** [comment]
Already partially implemented, moving to later milestone for when additional features are ready


_[Original comment](https://github.ugent.be/unipept/unipept/issues/349#issuecomment-10422) by @bmesuere on Thu Aug 07 2014 at 15:09._
