### ISSUE TITLE
pie chart tooltip on lineage tree nodes

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#35]
Add pie chart tooltip on lineage tree nodes; this way, it would become clear how the peptide hits are distributed over the children of the node that is hoovered over with the mouse.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/35) by @pdawyndt on Thu Jun 07 2012 at 14:50._
_Closed by @bmesuere on Thu Aug 07 2014 at 11:51._

**Comment by bmesuere** [comment]
A dedicated info panel to display this kind of information might be a better idea. See example at http://www.guardian.co.uk/world/interactive/2012/may/08/gay-rights-united-states


_[Original comment](https://github.ugent.be/unipept/unipept/issues/35#issuecomment-12) by @bmesuere on Thu Jun 07 2012 at 16:48._

**Comment by bmesuere** [comment]
Duplicate of #91 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/35#issuecomment-10415) by @bmesuere on Thu Aug 07 2014 at 11:51._
