### ISSUE TITLE
The road to open source

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#354]
Publish the github master branch on github.com
- [x] choose license MIT? Apache? -> MIT
- [x] create Unipept org on github.com
- [x] add more information to the readme (contributors, ...)
- [x] copy releases

_[Original issue](https://github.ugent.be/unipept/unipept/issues/354) by @bmesuere on Tue May 27 2014 at 22:09._
_Closed by @bmesuere on Fri Jun 06 2014 at 16:00._

**Comment by bmesuere** [comment]
There are some thing we want to keep private:
- google analytics
- stathat/cube logging
- email errors
- UGent cas login
- ?

How should we handle them? Add settings for each of them and create a separate branch to make public where those settings are empty?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/354#issuecomment-9944) by @bmesuere on Wed May 28 2014 at 10:01._

**Comment by bmesuere** [comment]
Rails 4.1 added http://edgeguides.rubyonrails.org/4_1_release_notes.html#config/secrets.yml which can be used to store keys and stuff.

As for features (such as CAS-login, and error emails), I would bundle them in a separate branch. (so that the master branch is always releasable, but you deploy master+feature).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/354#issuecomment-9945) by ghost on Wed May 28 2014 at 10:04._

**Comment by pdawyndt** [comment]
@bmesuere : we should add a disclaimer to the Unipept website (like Uniprot) now that the source code has been open sourced


_[Original comment](https://github.ugent.be/unipept/unipept/issues/354#issuecomment-10020) by @pdawyndt on Sat Jun 07 2014 at 10:13._
