### ISSUE TITLE
why is Pseudogulbenkiania not abbreviated

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#375]
I was clustering all Neisseriales genomes, and seemingly the heuristic for abbreviating genus names did not abbreviate "Pseudogulbenkiania sp. NH8B" as "P. sp. NH8B" as I would have expected.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/375) by @pdawyndt on Sat Jun 14 2014 at 10:37._
_Closed by @pdawyndt on Sat Jun 14 2014 at 12:57._

**Comment by bmesuere** [comment]
This is by design. It would be hard to infer The real name from just P. sp.
So when the second word is sp., I don't abbreviate the first.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/375#issuecomment-10069) by @bmesuere on Sat Jun 14 2014 at 10:42._

**Comment by pdawyndt** [comment]
OK


_[Original comment](https://github.ugent.be/unipept/unipept/issues/375#issuecomment-10070) by @pdawyndt on Sat Jun 14 2014 at 12:57._
