### ISSUE TITLE
branch swapping does not always work

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#376]
I created a tree including all 22 Vibrionales genomes, and spotted the following issues
- searching for the order _Vibrionales_ hits two orders that contain "vibrionales" in their name (_Bdellovibrionales_ and _Desulfovibionales_), but not the order _Vibrionales itself_
- swapping branches of the tree does modify the similarity matrix as expected, but the tree is not modified simultaneously; I have not observed this previously for other groups of organisms, but it seems to be consistent for the _Vibrionales_ tree
- lower half of the tree branch for the most similar pair of _Vibrio cholerae_ strains is not drawn

Note that the strain _Vibrio cholerae_ O395 has been sequences twice, so maybe that's causing the latter two issues (I would hope that internally the bioproject IDs are used, and not the names). If I remove one of the _Vibrio cholerae_ O395 sequences from the list, however, the last two issues seem to be resolved.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/376) by @pdawyndt on Sat Jun 14 2014 at 13:01._
_Closed by @bmesuere on Sat Jun 14 2014 at 19:37._

**Comment by pdawyndt** [comment]
Same problem with tree for the genus _Mycobacterium_, where _M. smegmatis_ str. MC2 155 has been sequenced twice.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/376#issuecomment-10071) by @pdawyndt on Sat Jun 14 2014 at 13:45._

**Comment by pdawyndt** [comment]
Same problem with tree for the genus _Burkholderia_, where _B. multivorans_ ATCC 17616 has been sequenced twice.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/376#issuecomment-10072) by @pdawyndt on Sat Jun 14 2014 at 15:46._

**Comment by bmesuere** [comment]
First issue is due to case sensitiveness of the search. Created issue #377 for this.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/376#issuecomment-10073) by @bmesuere on Sat Jun 14 2014 at 15:49._
