### ISSUE TITLE
fix UPGMA algorithm

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#378]
Merging clusters should be done by taking the weighted average using the cluster sizes as weights.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/378) by @bmesuere on Sat Jun 14 2014 at 17:20._
_Closed by @bmesuere on Sat Jun 14 2014 at 20:06._

**Comment by bmesuere** [comment]
The difference seems to be minimal. You can check by comparing the results from scruffy with the ones from unipept.ugent.be


_[Original comment](https://github.ugent.be/unipept/unipept/issues/378#issuecomment-10074) by @bmesuere on Sat Jun 14 2014 at 20:12._

**Comment by pdawyndt** [comment]
It is expected that the difference would be small, but it's better to use the correct implementation of the UPGMA algorithm, if we claim we use that algorithm


_[Original comment](https://github.ugent.be/unipept/unipept/issues/378#issuecomment-10075) by @pdawyndt on Sun Jun 15 2014 at 10:52._
