### ISSUE TITLE
add indication of genome size to peptidome clustering

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#379]
It might be handy to have an estimation of the genome size (measured as the number of peptides) together with the peptidome clustering. This could help to spot false "complete genomes" that were initially included in the analysis. Now this information is available from the Unique Peptide Finder view, but it requires swapping back and forth. 

As an example, make a clustering of all Mycobacterium genomes:
- the genome of _Mycobacterium yongonense_ 05-1390 is far from complete (or the annotation of the genome is wrong), since it has only 2508 peptides, compared to > 50.000 for the other genomes; this entry should clearly be removed from the cluster analysis
- the two _Mycobacterium tuberculosis_ RGTB genomes have 15-20.000 peptides less than the other _Mycobacterium tuberculosis_ genomes, which could hint on the fact that these are draft genomes, not complete genomes (or they should have a highly reduced genome). This could explain why these genomes do not cluster together with the other _Mycobacterium tuberculosis_ genomes.

To make this kind of inferences immediate, I would recommend adding a plot of the genome sizes below the similarity matrix (instead of the duplicated labels). This would avoid the need to switch back and forth between the clustering and the unique peptide finder.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/379) by @pdawyndt on Sun Jun 15 2014 at 11:30._

**Comment by pdawyndt** [comment]
As a somewhat related issue, the fact that the two "draft" _Mycobacterium tuberculosis_ still cluster closely with the other _Mycobacterium tuberculosis_ genomes, gives an indication that having the possibility to add high-quality draft genomes to the analysis might be interesting. However, instead of using the size of the union in the denominator of the similarity computation, we might use instead the minimum or average size of both genomes. 

We could make this a parameter that can be set by the user, and add a discussion on this in the article. For whole-genome clusterings of closely related organisms we could recommend using the size of the union in the denominator. For draft genomes, more remotely related organisms, or related organisms with varying genome sizes (e.g. _Clostridium_) we could recommend using the minimum or average size of both genomes.

If we define d_T(A,B) as interection(A, B) / T(A, B), with T in {min, avg, max, union}, then it always holds that intersection(A, B) <= min(A,B) <= avg(A,B) <= max(A, B) <= union(A, B), and thus 0 <= d_min(A, B) <= d_avg(A, B) <= d_max(A, B) <= d_union(A, B) <= 1.

Literature references where the minimum size of both genomes is used in the denominator of the distance function
- Snel B, Bork P, Huynen MA (1999). Genome phylogeny based on gene content. Nature Genetics 21, 108–110.
- Henz SR, Huson DH, Auch AF, Nieselt-Struwe K, Schuster SC (2005). Whole-genome prokaryotic phylogeny. Bioinformatics 21(10), 2329-2335.

Literature references where the average size of both genomes is used in the denominator of the distance function
- Auch AF, Henz SR, Holland BR, Göker M (2006). Genome BLAST distance phylogenies inferred from whole plastid and whole mitochondrion genome sequences. BMC Bioinformatics. 7, 350.
- Deloger M, El Karoui M, Petit MA (2009). A genomic distance based on MUM indicates discontinuity between most bacterial species and genera. Journal of Bacteriology 191, 91-99.

These last two references also have a discussion why using the average is better than using the minimum. Apparently the average allows greater sensitivity to variations due to gene loss and gene acquisition (which is necessary between close relatives). The union even gives greater sensitivity, since it does not "average out" gene loss by gene acquisition. So minimum-average-maximum-union would give different sensitivities to gene loss and gene acquisition, either naturally or due to the fact that some genomes are still high-quality drafts.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/379#issuecomment-10076) by @pdawyndt on Sun Jun 15 2014 at 11:41._

**Comment by bmesuere** [comment]
For now, the genome size is also shown in the tooltip of the similarity matrix


_[Original comment](https://github.ugent.be/unipept/unipept/issues/379#issuecomment-10077) by @bmesuere on Sun Jun 15 2014 at 11:42._

**Comment by pdawyndt** [comment]
@bmesuere : yes, this is how I spotted the differences initially, but having a clear overview over all sizes would seem like a helpful feature


_[Original comment](https://github.ugent.be/unipept/unipept/issues/379#issuecomment-10078) by @pdawyndt on Sun Jun 15 2014 at 11:48._
