### ISSUE TITLE
LCA still gives root in some cases

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#380]
If I select all Clostridium genomes, the LCA of the selected genomes is still indicated as "root".

_[Original issue](https://github.ugent.be/unipept/unipept/issues/380) by @pdawyndt on Sun Jun 15 2014 at 12:42._
_Closed by @bmesuere on Sun May 03 2015 at 11:28._

**Comment by bmesuere** [comment]
This is because one of the uniprot entries is labeled as `Clostridium phage phiSM101` which is classified as a virus: http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=396359


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-10079) by @bmesuere on Sun Jun 15 2014 at 13:00._

**Comment by bmesuere** [comment]
The guilty genome is Clostridium perfringens SM101


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-10080) by @bmesuere on Sun Jun 15 2014 at 13:02._

**Comment by pdawyndt** [comment]
@bmesuere If you check the bioproject page of [_Clostridium perfringens_ SM101](http://www.ncbi.nlm.nih.gov/bioproject/12521), you'll see that this project has [four sequence records in GenBank/RefSeq](http://www.ncbi.nlm.nih.gov/assembly/GCA_000013845.1), corresponding to
- one chromosome (taxon ID: 289380 = Clostridium perfringens SM101)
- two plasmids 
- one bacteriophage = virus infecting a bacterial cell (taxon ID: 396359 = Clostridium phage phiSM101)

As you'll see from the bioproject page of [_Clostridium perfringens_ SM101](http://www.ncbi.nlm.nih.gov/bioproject/12521), there's also a taxon ID associated to the bioproject itself: taxon ID 289380 = Clostridium perfringens SM101. So, we should take over the taxon ID from the bioproject, and not from one of the composing parts of the bioproject.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-10081) by @pdawyndt on Sun Jun 15 2014 at 17:32._

**Comment by bmesuere** [comment]
This isn't in the database yet. I will add it when the current uniprot update is done.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-10082) by @bmesuere on Sun Jun 15 2014 at 18:00._

**Comment by bmesuere** [comment]
Delayed till 2.4 because the format of the source file changed and there's no explanation about the new/changed fields


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-10289) by @bmesuere on Wed Jul 16 2014 at 19:06._

**Comment by bmesuere** [comment]
This was fixed by switching to assemblies.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/380#issuecomment-16979) by @bmesuere on Sun May 03 2015 at 11:28._
