### ISSUE TITLE
treeview: initial evaluation

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#385]
I like the colors per superkingdom. Here's some of the additional features I could think of upon first use of the tool.
- instead of opening a single level when clicking a node, try to open as much levels as would fit the viewport (as in the JIT tree) -> **very hard to do**
- sometimes clicking (or unintentional double clicking ???) showed the tree in most detailed zoom level (bug ???) -> **couldn't reproduce, must be due to double click**
- make focus node the new "root" of the tree: size of node should represent maximal node size and only sizes in subtree are relevant (nodes beyond subtree should be greyed out somehow) -> **already the case**
- synchronize focus point of sunburst, treemap and treeview; trace to focus point of all tree visualization could be show as bread crumbs -> **would need treemap rewrite in d3** (#54)
- base spacing between siblings based on the size of the circles around the nodes; this would avoid overlapping circles -> #388 
- right clicking a node should not pan the tree so that this node becomes the center of the viewport -> **center == highlight. performing an action on a node highlights it.**
- option to open a complete subtree -> **implement using shift+click** (#395)
- automatically bundle "other" group (which can be expanded upon request) -> #396
  - show at most x children and bundle remaining children in "other", 
  - only show children that have a certain abundance, and bundle remaining children in "other"
- include "unidentified" in root node -> **we don't do this in the other graphs**
- add extra information about nodes in popup menu (maybe also additional functionality that cannot be activated by clicking, double clicking or right clicking) -> **tooltip info is the same across graphs**
- options to sort siblings -> might be implemented with #396
  - alphabetically (default)
  - based on their abundance

advantages of treeview over treemap or sunburst
- possibility to focus on several branches at the same time
- both treeview and sunburst have a real representation of node sizes, whereas treemap uses an approximation of the size

_[Original issue](https://github.ugent.be/unipept/unipept/issues/385) by @pdawyndt on Fri Jul 04 2014 at 10:52._
_Closed by @bmesuere on Fri Aug 08 2014 at 18:47._

**Comment by bmesuere** [comment]
todo: evaluate + triage into separate issues


_[Original comment](https://github.ugent.be/unipept/unipept/issues/385#issuecomment-10356) by @bmesuere on Mon Aug 04 2014 at 14:12._

**Comment by bmesuere** [comment]
Added comments to the separated items and created issues for the ones to implement. Closing this one for now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/385#issuecomment-10439) by @bmesuere on Fri Aug 08 2014 at 18:47._
