### ISSUE TITLE
expand all child nodes in treeview

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#395]
let `shift + click` expand all nodes. Implement using `d3.event.shiftKey`.
disadvantages:
- not discoverable
- doesn't work on touch devices

_[Original issue](https://github.ugent.be/unipept/unipept/issues/395) by @bmesuere on Fri Aug 08 2014 at 18:35._
_Closed by @bmesuere on Mon Apr 27 2015 at 12:04._

**Comment by pdawyndt** [comment]
@bmesuere  once all nodes have been expanded, you can collapse them by clicking the root node, but after clicking the root node (not shift+click) they are again expanded fully; perhaps we could also make a distinction in collapsing the node between click (collapse, but preserve status when expanding) and shift+click (collapse and remove expanded state)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/395#issuecomment-15421) by @pdawyndt on Tue Mar 31 2015 at 18:38._
