### ISSUE TITLE
APIs and CLI are down 

### ISSUE THREAD

**Issue by Thys3Potgieter** [unipept/unipept#4]
Hi Team, 

The example get request from the website fails, and the same error appears in the cli,

http://api.unipept.ugent.be/api/v1/pept2prot.json?input[]=AIPQLEVARPADAYETAEAYR#

Error: Web application could not be started

Please have a look?

Thank you, Thys

**Comment by bmesuere** [comment]
Thanks for reporting. It seems like the database crashed for some reason. Everything should be working again now.

If you experience other issues, please let us know!

**Comment by Thys3Potgieter** [comment]
Thanks!
