### ISSUE TITLE
go cross references are missing

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#414]
Since the last run of the uniprot parser, the go_cross_references are missing. There probably was a change in the uniprot data format.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/414) by @bmesuere on Wed Sep 17 2014 at 10:02._
_Closed by @ninewise on Tue Jan 20 2015 at 15:15._

**Comment by ninewise** [comment]
I searched around in the `uniprot_sprot.xml` file, I suppose the followwing means the type is now "GO" in stead of "Go"?

```
 $ cat uniprot_sprot.xml | grep 'dbReference' | grep 'type="Go"' | head
 $ cat uniprot_sprot.xml | grep 'dbReference' | grep 'type="GO"' | head
  <dbReference id="GO:0033644" type="GO">
  <dbReference id="GO:0016021" type="GO">
  <dbReference id="GO:0005737" type="GO">
  <dbReference id="GO:0030659" type="GO">
  <dbReference id="GO:0005829" type="GO">
  <dbReference id="GO:0005576" type="GO">
  <dbReference id="GO:0005634" type="GO">
  <dbReference id="GO:0051219" type="GO">
  <dbReference id="GO:0005515" type="GO">
  <dbReference id="GO:0019901" type="GO">
```

I'll change this for now, kindly let me know if there are not the actual go_cross_references.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/414#issuecomment-11577) by @ninewise on Wed Oct 29 2014 at 22:12._

**Comment by bmesuere** [comment]
yes indeed. For example, at http://www.uniprot.org/uniprot/H0F9I0, you can see the GO terms under the function header. If you click Format > XML you can see the corresponding xml entry with the GO references.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/414#issuecomment-11579) by @bmesuere on Thu Oct 30 2014 at 09:57._
