### ISSUE TITLE
SEQUENCE was in the production database

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#441]
The sequence `SEQUENCE` was in the database, probably due to a faulty header row import.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/441) by @bmesuere on Thu Dec 04 2014 at 17:15._
_Closed by @bmesuere on Sun Dec 14 2014 at 15:36._

**Comment by bmesuere** [comment]
this seems to be an issue for all tables


_[Original comment](https://github.ugent.be/unipept/unipept/issues/441#issuecomment-12731) by @bmesuere on Sun Dec 14 2014 at 15:30._

**Comment by bmesuere** [comment]
@ninewise can you check your branch to make sure the problem doesn't occur there?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/441#issuecomment-12733) by @bmesuere on Sun Dec 14 2014 at 15:38._

**Comment by ninewise** [comment]
I grepped SEQUENCE in the sequences table, and I can't seem to find it. This should be fixed, unless you meant another table.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/441#issuecomment-12735) by @ninewise on Mon Dec 15 2014 at 10:27._
