### ISSUE TITLE
refactor data pipeline

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#451]
![img_20150115_152755_1024](https://github.ugent.be/github-enterprise-assets/0000/0007/0000/0314/dd9ec6e8-9cc4-11e4-88e0-70199a511b10.png)
- never output header lines + use \N for null
- always output `.gz` files
- convert taxonLoader. to eliminate the database and create taxons.tsv
- refactor peptideLoader to extract lineage calculation
- check which tables need to be loaded for genome loading
- rewrite bash files

_[Original issue](https://github.ugent.be/unipept/unipept/issues/451) by @bmesuere on Thu Jan 15 2015 at 15:44._
_Closed by @ninewise on Fri Mar 20 2015 at 13:40._

**Comment by ninewise** [comment]
![backend schema 3](https://github.ugent.be/github-enterprise-assets/0000/0056/0000/0315/51901fb2-9d5a-11e4-8804-5c811cf3f708.png)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/451#issuecomment-13534) by @ninewise on Fri Jan 16 2015 at 09:33._

**Comment by ninewise** [comment]
There may be something incorrect about this chart. I forgot how t in the old version, the lineages are only calculated for taxons encountered during the parsing of uniprot. In the chart however, the `lineages.sh` script is independent of the `peptideLoader.java` program.

To correct this, the easiest would probably be to let the peptideLoader output a new `taxons.tsv` file, including only the encountered taxons. I suspect the unused taxons are ignored in the rest of the program, anyway.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/451#issuecomment-13631) by @ninewise on Fri Jan 23 2015 at 17:36._

**Comment by bmesuere** [comment]
@ninewise with the taxonomy and taxa2lca command of the api in mind, we decided that from now on we'll store the lineage of all taxa and not only the encountered ones.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/451#issuecomment-13634) by @bmesuere on Fri Jan 23 2015 at 18:31._

**Comment by ninewise** [comment]
Fixed in f9d5b4c820674482b8ca0b116c60df6d745958a7


_[Original comment](https://github.ugent.be/unipept/unipept/issues/451#issuecomment-14893) by @ninewise on Fri Mar 20 2015 at 13:40._
