### ISSUE TITLE
additional NCBI links from UniProt ID

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#457]
If we have links from the UniProt ID to NCBI assemblies, bioprojects, biosamples, ..., we might as well show them as additional linkouts from the UniProt IDs

_[Original issue](https://github.ugent.be/unipept/unipept/issues/457) by @pdawyndt on Wed Feb 04 2015 at 15:04._
_Closed by @bmesuere on Fri Jul 03 2015 at 15:54._

**Comment by bmesuere** [comment]
We don't have bioprojects and biosamples anymore, the NCBI assemblies would require several extra queries.
We should look into this when we add more metadata from uniprot. Closing this for now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/457#issuecomment-18859) by @bmesuere on Fri Jul 03 2015 at 15:54._
