### ISSUE TITLE
New information added in #449 contains NULL in some cases

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#459]
For example:

```
>|0,VEEFK,Q9UNT9,9606,Homo sapiens,,,NM_001002800.2 NM_001288753.1 NM_005496.3,NP_001002800.1 NP_001275682.1 NP_005487.3,AB019987 AL136877 AL833949 AC024221 CH471052 CH471052 AF092564,BAA73535.1 CAB66811.1 CAD38803.1 NULL EAW78639.1 EAW78640.1 AAC72361.1
>|0,VEEFK,E9PD53,9606,Homo sapiens,,,NM_001288753.1,NP_001275682.1,AC024221,NULL
>|0,VEEFK,W5N1C6,7918,Lepisosteus oculatus,,,,,AHAT01036282 AHAT01036283 AHAT01038403 AHAT01038404 AHAT01038405 AHAT01038406,NULL NULL NULL NULL NULL NULL
>|0,VEEFK,G1T881,9986,Oryctolagus cuniculus,,,,,AAGW02014766 AAGW02014767 AAGW02014768 AAGW02014769 AAGW02014770,NULL NULL NULL NULL NULL
>|0,VEEFK,F7ICG2,9483,Callithrix jacchus,1.1.1.42,,,,ACFV01149831,NULL
>|0,VEEFK,W5QCD6,9940,Ovis aries,1.1.1.42,,,,AMGL01055585,NULL
>|0,VEEFK,H0XC28,30611,Otolemur garnettii,1.1.1.42,,XM_003784989.1,XP_003785037.1,AAQR03032214,NULL
>|0,VEEFK,G1PV67,59463,Myotis lucifugus,1.1.1.42,,,,AAPE02061662 AAPE02061663 AAPE02061664,NULL NULL NULL
>|0,VEEFK,H0ZHA7,59729,Taeniopygia guttata,1.1.1.42,,,,ABQF01010245 ABQF01010246 ABQF01010247,NULL NULL NULL
>|0,VEEFK,D3YVY3,10090,Mus musculus,,,,,AC101869 AC164079,NULL NULL
```

Is this expected behaviour?

_[Original issue](https://github.ugent.be/unipept/unipept/issues/459) by @silox on Sat Feb 14 2015 at 11:01._
_Closed by @bmesuere on Mon Feb 16 2015 at 16:40._

**Comment by bmesuere** [comment]
The database also contains NULL, so this might be an issue with the parser.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/459#issuecomment-13887) by @bmesuere on Sat Feb 14 2015 at 15:02._

**Comment by bmesuere** [comment]
The corresponding Uniprot entries don't contain a protein id for these insdc id's, so the null in the output is expected.
An example can be seen at http://www.uniprot.org/uniprot/W5QCD6 ("no translation available").

@pdawyndt Any idea why these are missing?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/459#issuecomment-13889) by @bmesuere on Sat Feb 14 2015 at 15:13._

**Comment by pdawyndt** [comment]
@bmesuere @silox  it seems that these proteins have not been annotated in the INSDC database, so they must have been inferred by a gene prediction that is done while generating the UniProt records from the INSDC records; apparently they run their own gene prediction pipeline, instead of (only) relying on the annotations as done in INSDC


_[Original comment](https://github.ugent.be/unipept/unipept/issues/459#issuecomment-15419) by @pdawyndt on Tue Mar 31 2015 at 18:24._
