### ISSUE TITLE
add protein names to tryptic peptide analysis

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#465]
The table showing the protein matches for a tryptic peptide could include the name of the proteins. This could be an indication of the function of the proteins.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/465) by @pdawyndt on Mon Mar 09 2015 at 22:09._
_Closed by @bmesuere on Mon May 04 2015 at 09:30._

**Comment by bmesuere** [comment]
@ninewise can you include the protein name in the parser? It should be in the xml under protein > recommendedName > fullName. In the output/database, I propose to add a column between `type` and `protein`


_[Original comment](https://github.ugent.be/unipept/unipept/issues/465#issuecomment-14477) by @bmesuere on Tue Mar 10 2015 at 08:43._

**Comment by ninewise** [comment]
OK, I'll see to it.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/465#issuecomment-14588) by @ninewise on Thu Mar 12 2015 at 13:15._
