### ISSUE TITLE
export biodiversity analysis results in BIOM format

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#468]
Provide the option to export the biodiversity analysis results in BIOM format.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/468) by @pdawyndt on Fri Mar 13 2015 at 15:32._

**Comment by bmesuere** [comment]
https://github.com/biocore/biom-format


_[Original comment](https://github.ugent.be/unipept/unipept/issues/468#issuecomment-14712) by @bmesuere on Sat Mar 14 2015 at 12:16._
