### ISSUE TITLE
add more functional information into Unipept

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#473]
From a brainstorm this morning with Klaas Van De Poele, we figured out that for the tryptic peptide `ENFVYIAK`, UniProt record `E1U3Z1` is missing GO annotations, but it has links to InterPro domains. Since InterPro provides a mapping to GO ([InterPro2GO](http://www.ebi.ac.uk/GOA/InterPro2GO)), it is strange that no GO annotations were included in the UniProt record. But given the mapping,and the addition of the InterPro cross-references to Unipept, we could make the mapping ourselves.

As we are gradually adding more functional cross-references to Unipept, we might consider to add all available cross-references from the UniProt record (or at least those in the category "Family domain databases"). Instead of adding another table for each cross-referenced database in Unipept, we might merge all cross-references in a single table, that also has a column to indicate what database the cross-reference is referring to.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/473) by @pdawyndt on Thu Mar 19 2015 at 22:05._

**Comment by bmesuere** [comment]
Some considerations:
- We need to make a good estimation of the length of the possible cross_reference_id field and of the number of rows we would have (100M entries \* 10-20 cross references?)
- A single table for all cross references is not a viable option. Some cross references are used in joins, so we need an index on them for performance reasons. A single table for all cross references would contain 1+ billion rows. We will already have to create an index on the uniprot_entry_id and creating an extra index on a text column in a table of that size is not a good idea. **tl;dr**: cross references used in queries must have their own table, the rest can be pooled in one table.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/473#issuecomment-14952) by @bmesuere on Sat Mar 21 2015 at 19:29._

**Comment by bmesuere** [comment]
More functional data can be found at http://proteininformationresource.org/pirwww/dbinfo/


_[Original comment](https://github.ugent.be/unipept/unipept/issues/473#issuecomment-17310) by @bmesuere on Fri May 08 2015 at 14:43._
