### ISSUE TITLE
documenting the API server benchmark

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#479]
Dataset: http://meta.genomics.cn/metagene/meta/dataTools
Command: `time find . -maxdepth 1 -name "IGC.pep*" | xargs -P8 -L1 ./run.sh`
- 3 threads: 138 minutes
- 8 threads: 89 minutes (70K requests/15 minutes, 100 peptides/request)
  - apparently there was another user on the server
  - network usage was 2MB/s upload, 1MB/s download
- 8 threads: 65 minutes (550K requests/15 minutes, 100 peptides/request, tweaked server settings)
  - there was another user on the server
  - the number of requests on stathat seems unreliable?

todo
- try 16 threads
- try 1000/10.000/100.000 peptides per request
- increase PassengerMaxPoolSize (https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerMaxPoolSize)
- increase worker MPM settings (http://www.genericarticles.com/mediawiki/index.php?title=How_to_optimize_apache_web_server_for_maximum_concurrent_connections_or_increase_max_clients_in_apache)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/479) by @bmesuere on Wed Apr 01 2015 at 10:34._

**Comment by pdawyndt** [comment]
@bmesuere @silox during a test Tom ran this morning, setting the batch size to 100.000 peptides apparently gives an error on the server (POST message too large?).


_[Original comment](https://github.ugent.be/unipept/unipept/issues/479#issuecomment-15724) by @pdawyndt on Tue Apr 07 2015 at 14:36._
