### ISSUE TITLE
complete proteomes

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#482]
@ninewise @bmesuere @silox UniProt also provides a [list of complete proteomes](http://www.uniprot.org/proteomes/). Instead of retrieving the "complete genomes" from genbank, we might also work from this list. However, this would only include the complete genomes (not the partial ones). At least, we could do a check to see how much "complete proteomes" the two resources have in common.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/482) by @pdawyndt on Tue Apr 07 2015 at 13:12._
_Closed by @bmesuere on Sun Jan 24 2016 at 13:18._

**Comment by pdawyndt** [comment]
It seems that all UniProt proteomes are also linked to to an Assembly, so probably they have also built the proteome database from the same resource as we have. It might be worthwile to check if Unipept has the same list of "complete proteomes" as UniProt after the new data has been included into Unipept.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/482#issuecomment-15716) by @pdawyndt on Tue Apr 07 2015 at 13:33._

**Comment by pdawyndt** [comment]
Instead of only providing a link to the Assembly record, we could also include a link to the UniProt proteome record.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/482#issuecomment-15717) by @pdawyndt on Tue Apr 07 2015 at 13:33._

**Comment by pdawyndt** [comment]
If the two list differ not too much, we could provide the option to upload one or mores proteomes directly from the [UniProt proteomes](http://www.uniprot.org/proteomes/), by providing a list of proteome IDs (or directly in the format that can be exported from Uniprot proteomes: `Proteome ID`, `Organism`, `Taxonomic identifier` and `Last modified`, separated by tabs)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/482#issuecomment-15726) by @pdawyndt on Tue Apr 07 2015 at 14:41._

**Comment by bmesuere** [comment]
Unipept uses UniProt proteomes since version 3.1


_[Original comment](https://github.ugent.be/unipept/unipept/issues/482#issuecomment-24352) by @bmesuere on Sun Jan 24 2016 at 13:18._
