### ISSUE TITLE
genus name abbreviations not always applied

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#483]
@bmesuere I have uploaded the following two custom proteomes into the Peptidome Analysis tools of Unipept:
- [Acinetobacter baumannii AC30](http://www.uniprot.org/proteomes/UP000006331)
- [Acinetobacter baumannii NCGM 237](http://www.uniprot.org/proteomes/UP000016884)

However, only the genus name of the second proteome is abbreviated into A., whereas the name of the first proteome is not abbreviated at all. What is the reason for this?

_[Original issue](https://github.ugent.be/unipept/unipept/issues/483) by @pdawyndt on Tue Apr 07 2015 at 13:25._
_Closed by @bmesuere on Tue Apr 07 2015 at 14:50._

**Comment by bmesuere** [comment]
The names of custom genomes should never be abbreviated since we don't know if the user entered a species name of something like "genome A42".
I can't reproduce this in the production version. Are you sure you added 2 custom genomes?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/483#issuecomment-15721) by @bmesuere on Tue Apr 07 2015 at 14:07._

**Comment by pdawyndt** [comment]
@bmesuere I've tried it again, and when I include a genome with the name "Acinetobacter baumannii NCGM 237", it is spelled in full in the list of analyzed genomes, but it is spelled as "A. baumannii NCGM 237" both in the clustering tool and the Unique Peptide Finder. The genome named "Acinetobacter baumannii AC30" was never abbreviated.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/483#issuecomment-15722) by @pdawyndt on Tue Apr 07 2015 at 14:32._

**Comment by bmesuere** [comment]
I reviewed the code and custom names aren't abbreviated except if the name is longer 30 chars. The idea behind not abbreviating custom names is that you can always abbreviate yourself where needed.
I can remove the length exception to make things more consistent.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/483#issuecomment-15725) by @bmesuere on Tue Apr 07 2015 at 14:41._

**Comment by pdawyndt** [comment]
@bmesuere Given that I was surprised to see different behaviour for two custom proteomes, I believe it would be more transparent to remove the length abbreviation.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/483#issuecomment-15727) by @pdawyndt on Tue Apr 07 2015 at 14:47._
