### ISSUE TITLE
some peptidomes never get loaded

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#485]
If I upload all genomes of the Burkholderiales (112 peptidomes; parent node of Burkholderia), than some of the genomes never get loaded in the browser. It seems that as soon as the application starts computing the pairwise similarities between the uploaded genomes, this blocks the download of any peptidomes that haven't been downloaded up to this point.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/485) by @pdawyndt on Tue Apr 07 2015 at 15:24._
_Closed by @bmesuere on Sun Apr 26 2015 at 12:42._

**Comment by pdawyndt** [comment]
Same holds if I try to load the same genomes in the Unique Peptide Finder, so it must be unrelated to the point where the pairwise similarities start to be computed.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/485#issuecomment-15753) by @pdawyndt on Wed Apr 08 2015 at 10:45._

**Comment by bmesuere** [comment]
When adding over 100 genomes, the memory needed for all genomes becomes a problem and the application becomes unstable. There's not much we can do about this, so closing this for now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/485#issuecomment-16653) by @bmesuere on Sun Apr 26 2015 at 12:42._
