### ISSUE TITLE
selection blocks after loading one species

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#486]
On my ipad, the button to add species from the drop down list remains inactivated (button label is loading...) after having selected one species. Clearing the list of selected proteomes does restore the original state of the button.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/486) by @pdawyndt on Sun Apr 12 2015 at 08:37._
_Closed by @bmesuere on Sun Apr 26 2015 at 12:34._

**Comment by bmesuere** [comment]
Is this on the production version or on nibbler?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/486#issuecomment-15917) by @bmesuere on Sun Apr 12 2015 at 12:24._

**Comment by pdawyndt** [comment]
@bmesuere production


_[Original comment](https://github.ugent.be/unipept/unipept/issues/486#issuecomment-15932) by @pdawyndt on Mon Apr 13 2015 at 08:26._

**Comment by bmesuere** [comment]
Not reproducible + the species selector was removed in 2.6. Closing this for now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/486#issuecomment-16652) by @bmesuere on Sun Apr 26 2015 at 12:34._
