### ISSUE TITLE
wrong color codes in similarity matrix

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#488]
^When clustering all genomes of the genus Treponema, I got a result where the color coding of the cells on the top row was not correct. The similarity values themselvers where correct and all values op the top row (except for the first one) were below 2%, but still they were colored in darker blue shades. Even cells with a lower similarity value were darker on the top row than some neighbouring cells (on the top row) with slightly lower similarity.

I took the screen shot shown below, since this bug is not reproducible. I tried it at least another five times, each time giving correct results.

![treponema](https://github.ugent.be/github-enterprise-assets/0000/0006/0000/0500/6cab5a8c-e1c5-11e4-8fff-f8b3dece361e.png)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/488) by @pdawyndt on Mon Apr 13 2015 at 10:13._
_Closed by @bmesuere on Sun Apr 26 2015 at 12:33._

**Comment by bmesuere** [comment]
Not reproducible and a lot of this code was rewritten for 2.6 so closing this for now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/488#issuecomment-16651) by @bmesuere on Sun Apr 26 2015 at 12:33._
