### ISSUE TITLE
`unipept taxonomy` removes duplicates

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#490]
When querying the taxonomy with duplicate IDs, only one result per ID is returned. For example:
http://api.unipept.ugent.be/api/v1/taxonomy.json?input[]=817&input[]=817. Pept2prot doesn't do this as can be seen in http://api.unipept.ugent.be/api/v1/pept2prot.json?input[]=AIPQLEVARPADAYETAEAYR&input[]=APVLSDSSCK&input[]=AIPQLEVARPADAYETAEAYR. 

https://github.ugent.be/unipept/unipept/blob/develop/app/controllers/api/api_controller.rb#L141

_[Original issue](https://github.ugent.be/unipept/unipept/issues/490) by @silox on Tue Apr 14 2015 at 11:17._
_Closed by @bmesuere on Tue May 19 2015 at 21:01._

**Comment by bmesuere** [comment]
Possible solution:

```
taxons = User.find(`@input`).group_by(&:id)
respond_with `@input`.flat_map{ |id| taxons[id] }
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/490#issuecomment-15970) by @silox on Tue Apr 14 2015 at 13:32._

**Comment by pdawyndt** [comment]
@silox for consistency reasons, IMO it would seem logical that the API calls never remove duplicates; so I agree with making the modifications to assure this


_[Original comment](https://github.ugent.be/unipept/unipept/issues/490#issuecomment-16131) by @pdawyndt on Fri Apr 17 2015 at 12:35._
