### ISSUE TITLE
filter genomes based on "type strain/type specimen"

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#491]
@bmesuere Please read through the following paper:

Federhen, S. (2014). [Type material in the NCBI Taxonomy Database](http://nar.oxfordjournals.org/content/early/2014/11/14/nar.gku1127.full). Nucleic acids research, gku1127.

_application of shared k-mers (and ANI-like measure that references the Meier-Kolthoff et al. 2013 paper) to type strain (mainly bacteria, but also others); example of Dickeya and Klebsiella oxytoca/Raoultella ornithinolytica; could serve as a reference for the type strain filtering; need to check how the type strain filtering can be implemented in Unipept; currenly does not seem to be directly annotated on the assemblies, but may be derived using a detour_

Scott Federhen has sent me this article, together with an invitation to participate in a mini-symposium at the NCBI about the topic of "sequence from type". The article has some use cases that we could include in the peptidome-clustering paper (I have added it to the literature list of this paper), but it would also be quite interesting to have the "type strain" information available for the proteomes. I haven't been able to check how easy this data is accessible for the assembly records (GenBank seems to be down today), but the article seems to indicate that this information is either available directly with the assembly records, or can be found using some of its links. It would definitely be interesting to have this information an use it for filtering the genomes especially when the number of available genomes keeps growing. We could also flag the genomes that are from type material in the clustering en unique peptide finder.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/491) by @pdawyndt on Fri Apr 17 2015 at 12:32._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

**Comment by bmesuere** [comment]
The data was added and is filterable by using `is:type`


_[Original comment](https://github.ugent.be/unipept/unipept/issues/491#issuecomment-16713) by @bmesuere on Mon Apr 27 2015 at 19:45._
