### ISSUE TITLE
issues with peptidome-based clustering tool

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#496]
I checked the new version of the peptidome-based clustering for all 108 assemblies of the genome _Burkholderia_, and here are some issues I discovered:
- [x] some assemblies are missing because their sequence records are a composition of other sequence records whose accession numbers cannot be linked directly to the assembly using the information that is in the Unipept database; some examples _B. ubonensis_ Bu, _B. thailandensis_ E264 (2 assemblies available of this strain, but only one available from Unipept), _B. thailandensis_ Bt4, _B. thailandensis_ TXDOH, _B. oklahomensis_ C6786, _B. oklahomensis_ CDC E0147
- [x] the type strain of _B. phenoliruptrix_ (AC1100) has an assembly which is not available from Unipept (because the sequence records are linked to other sequence records; assembly ID GCA_000416445.1)
- [x] the `minimum` metric is the only one that does not properly separate _B. mallei_ from _B. pseudomallei_
- [x] assembly of _B. cenocepacia_ J2315 is not annotated by NCBI as derived from type material (reported to Scott Federhen)
- [x] assembly of _B._ sp. MP-1 is should have species name _Burkholderia jiangsuensis_ since it is the type strain of this species (reported to Scott Federhen; fixed by Scott Federhen)

Other findings: three _Burkholderia_ assemblies have highly reduces genomes
- Candidatus _Burkholderia kirkii_ UZHbot 1 (only 10% size of other _Burkholderia_ genomes, only from its species that has been sequenced)
- _Burkholderia cepacia_ JBK9 (only 60% size of other _Burkholderia_ genomes, clusters withing the _B. cepacia complex_)
- _Burkholderia rhizoxinica_ (only 60% size of other _Burkholderia_ genomes, only from its species that has been sequenced)

_[Original issue](https://github.ugent.be/unipept/unipept/issues/496) by @pdawyndt on Wed May 06 2015 at 20:35._

**Comment by pdawyndt** [comment]
Hi Peter:

Thanks for sending this along!

We’ve always had the facility to update entries like this,
where we can do it by synonymy (with the strain-specific informal name).

I’ve updated the entry in taxonomy -

  http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1458357

and cc’ed our bacterial taxonomist (who may edit it further).

Cheers,

:Scott

ps. this will be flagged as sequence from type with the next reindex -
    I usually do that once a week, on Mondays.

On May 6, 2015, at 12:02 PM, Peter Dawyndt Peter.Dawyndt`@UGent`.be wrote:

[Hide Quoted Text]
Scott,

One thing I forgot to say: this assembly

http://www.ncbi.nlm.nih.gov/assembly/GCA_000648925.1

is also marked as derived from type material. The taxon ID is assigned the name "Burkholderia sp. MP-1" and I assume it the type strain of Burkholderia jiangsuensis (published 2014). The draft genome was published in this paper

Liu XY et al., "Draft Genome Sequence of Burkholderia sp. Strain MP-1, a Methyl Parathion (MP)-Degrading Bacterium from MP-Contaminated Soil.", Genome Announc, 2014 May 22;2(3).

and the new species was described in this paper from later that year, by the same authors

LIU, X.-Y., LI, C.-X., LUO, X.-J., LAI, Q.-L. and XU, J.-H. 2014. Burkholderia jiangsuensis sp. nov., a methyl parathion degrading bacterium, isolated from methyl parathion contaminated soil. Int. J. Syst. Evol. Microbiol., 64, 3247-3253.

As I understood from your paper, NCBI now gives itself the possibility to update taxonomic names in the sequence databases, instead of relying on the depositors of the sequences. So maybe this is an example of a name that could be updated (no discussion about the correct identification, since this is a sequence of the type material).

Best regards,

Peter


_[Original comment](https://github.ugent.be/unipept/unipept/issues/496#issuecomment-17199) by @pdawyndt on Wed May 06 2015 at 20:37._

**Comment by bmesuere** [comment]
@pdawyndt Can this be closed or is this still relevant for the peptidome clustering paper?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/496#issuecomment-24497) by @bmesuere on Mon Feb 01 2016 at 13:52._
