### ISSUE TITLE
browser refresh converts taxon name back to taxon:taxon_id

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#498]
If a taxon name is specied as a filter criterium for selecting proteomes, after which the browser is refreshed (CTRL+R), the name is replaced by `taxon:taxon_id`.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/498) by @pdawyndt on Fri May 08 2015 at 13:39._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

**Comment by bmesuere** [comment]
This is a bug in Firefox related to https://bugzilla.mozilla.org/show_bug.cgi?id=654072


_[Original comment](https://github.ugent.be/unipept/unipept/issues/498#issuecomment-17306) by @bmesuere on Fri May 08 2015 at 13:42._

**Comment by pdawyndt** [comment]
Along the same lines: if a taxon has been selected, the edit box for filtering proteomes has the focus, and one tries to copy its content to the clipboard, the taxon name is copied as `taxon:taxon_id`. Observed in FF.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/498#issuecomment-17624) by @pdawyndt on Tue May 12 2015 at 22:00._
