### ISSUE TITLE
Unipept: API request failed

### ISSUE THREAD

**Issue by blue717** [unipept/unipept#5]
Hi,

I am running unipept in my laptop using this command line:
unipept pept2lca -i file1.txt -e -o file1.csv
but I got this error message:
API request failed! log can be found in /.unipept/unipept.log
and the log file looks like that:
Got 404: <!DOCTYPE html>
<html>

  <head>
    <title>The page you were looking for doesn't exist (404)</title>
    <style type="text/css">
      body {
        background-color: #fafafa;
        color: #333;
        text-align: center;
        font-family: arial, sans-serif;
      }

      div.dialog {
        width: 25em;
        padding: 16px;
        margin: 4em auto 0 auto;
        background-color: white;
        box-shadow: 0 8px 10px -5px rgba(0,0,0,.14),0 16px 24px 2px rgba(0,0,0,.098),0 6px 30px 5px rgba(0,0,0,.084);
        border-radius: 2px;....

It was working fine for me before.
Please, I wonder what it is the issue?

Thanks,

**Comment by bmesuere** [comment]
Everything seems to be up and running on the server side. Can you try if this request works?
```
unipept pept2lca AALTER
```

If it does, can you give me the output of `unipept config host`, `unipept --version` and the first few lines of you input file?

**Comment by blue717** [comment]
I ran your command, I got this message:

$ unipept pept2lca AALTER
<!DOCTYPE html>
<html>

  <head>
    <title>The page you were looking for doesn't exist (404)</title>
    <style type="text/css">
      body {
        background-color: #fafafa;
        color: #333;
        text-align: center;
        font-family: arial, sans-serif;
      }

      div.dialog {
        width: 25em;
        padding: 16px;
        margin: 4em auto 0 auto;
        background-color: white;
        box-shadow: 0 8px 10px -5px rgba(0,0,0,.14),0 16px 24px 2px rgba(0,0,0,.098),0 6px 30px 5px rgba(0,0,0,.084);
        border-radius: 2px;
      }

      h1 {
        font-size: 100%;
        color: #f00;
        line-height: 1.5em;
      }

      .dialog img {
        width: 10em;
      }

    </style>
  </head>

  <body>
    
    <div class="dialog">
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
      <img src="/images/404.png" alt="404" />
    </div>
  </body>

</html>
API request failed! log can be found in /Users/.unipept/unipept-2018-07-24-12:05:54.log


and this is the contain of the log file:

Got 404: <!DOCTYPE html>
<html>

  <head>
    <title>The page you were looking for doesn't exist (404)</title>
    <style type="text/css">
      body {
        background-color: #fafafa;
        color: #333;
        text-align: center;
        font-family: arial, sans-serif;
      }

      div.dialog {
        width: 25em;
        padding: 16px;
        margin: 4em auto 0 auto;
        background-color: white;
        box-shadow: 0 8px 10px -5px rgba(0,0,0,.14),0 16px 24px 2px rgba(0,0,0,.098),0 6px 30px 5px rgba(0,0,0,.084);
        border-radius: 2px;
      }

      h1 {
        font-size: 100%;
        color: #f00;
        line-height: 1.5em;
      }

      .dialog img {
        width: 10em;
      }

    </style>
  </head>

  <body>
    
    <div class="dialog">
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
      <img src="/images/404.png" alt="404" />
    </div>
  </body>

</html>

Request headers: {:method=>:post, :body=>{:input=>["AALTER"], :equate_il=>false, :extra=>false, :names=>false}, :accept_encoding=>"gzip", :headers=>{"User-Agent"=>"Unipept CLI - unipept 1.3.0", "Expect"=>""}, :maxredirs=>50}
Request body:
input[0]=AALTER&equate_il=false&extra=false&names=false

**Comment by bmesuere** [comment]
sorry, I meant doesn't work instead of does work in my previous reply. Can you give me the output of 
```
unipept --version
```
and 
```
unipept config host
```

**Comment by bmesuere** [comment]
Aha, that seems to be the issue, the host should simply be http://api.unipept.ugent.be.
You can run `unipept config host http://api.unipept.ugent.be` to set it.

Afterwards everything should work.

**Comment by blue717** [comment]
It works.
Thank you very much.
