### ISSUE TITLE
similarity measures: average vs extra

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#500]
In clustering all 16 _Agrobacterium_ genomes, I can see not a single difference between the similarity values computed with the **extra** similarity measure and the _average_ similarity measure. Can you check if there's nothing wrong here?

I also recommend to rename the similarity measures, and sort them from largest to smallest:
- minimum 
- arithmetic mean
- quadratic mean (variant: name to be adjusted)
- maximum
- union

I would also recommend to take the minimum as the default setting.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/500) by @pdawyndt on Tue May 19 2015 at 08:41._
_Closed by @bmesuere on Fri Jul 03 2015 at 15:50._

**Comment by bmesuere** [comment]
The tooltip does shows a difference in similarity. Because it's often less than 0.1%, this is not visible in the similarity matrix.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/500#issuecomment-18857) by @bmesuere on Fri Jul 03 2015 at 15:50._
