### ISSUE TITLE
Use UniProt proteomes as peptidome analysis data source

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#532]
UniProt offers a list of proteomes on their website. These contain all UniProt entries that are linked to sequenced organisms; exactly what we need for the peptidome analysis. In the past there were some serious issues with these proteomes that prevented us from using them: only a limited set was offered and some proteomes didn't represent the full genome.

As of now, these issues seem to be resolved. Some stats:
- 3264 reference proteomes
- 7374 non-reference proteomes
- 6119 Bacteria
- 3,379 Viruses
- 314 Archaea
- 825 Eukaryota

At this moment, Unipept contains information on 7715 proteomes of which some are incomplete. 

Switching to UniProt proteomes would increase the total number of proteomes from 7715 to 10638. Because of the redundancy removal in UniProt, this probably means that the number of proteomes per species will decrease. Some examples:

| species | # in Unipept | # complete in Unipept | # UniProt proteomes |
| --- | --: | --: | --: |
| A. Baumannii | 135 | 16 | 31 |
| E. Coli | 260 | 61 | 151 |
| S. Aureus | 38 | 22 | 20 |
| B. Cereus | 20 | 16 | 107 |
| L. Lactis | 23 | 13 | 18 |

_[Original issue](https://github.ugent.be/unipept/unipept/issues/532) by @bmesuere on Mon Nov 23 2015 at 21:31._
_Closed by @bmesuere on Sat Dec 05 2015 at 14:02._

**Comment by pdawyndt** [comment]
@bmesuere good news !!


_[Original comment](https://github.ugent.be/unipept/unipept/issues/532#issuecomment-21579) by @pdawyndt on Tue Nov 24 2015 at 08:32._

**Comment by bmesuere** [comment]
implemented in #533


_[Original comment](https://github.ugent.be/unipept/unipept/issues/532#issuecomment-22250) by @bmesuere on Sat Dec 05 2015 at 14:02._
