### ISSUE TITLE
idea for proteome compression

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#539]
The proteomes are a sorted lists of integers and are sent to the client in JSON format, being text. This means that `6039234` takes up 7 times the space of `6`. Since the integers are sorted, a proteome of 100.000 peptides has an average gap between the peptides of 4000 (400M/100K). This is the worst case scenario, most of the time the peptide ids will be sequential.

All this means that performing a delta encoding on the peptide list would probably reduce the size of the JSON encoded array.

Pros:
- no extra server side cost since they are cached
- they are also stored as text in the database, so this would mean less storage space
- fewer data to fetch from the database and send to the client 

Cons:
- the client needs to decode the list 

Implemented in 6aef794

_[Original issue](https://github.ugent.be/unipept/unipept/issues/539) by @bmesuere on Wed Dec 02 2015 at 10:44._
_Closed by @bmesuere on Wed Dec 02 2015 at 17:14._

**Comment by bmesuere** [comment]
Compression seems to work. The gzip id size column is the current transfer size, the gzip delta column is the potential size.

| Organism | # peptides | peptide size | id size | gzip id size | delta size | gzip delta size | ratio |
| :-- | --: | --: | --: | --: | --: | --: | --: |
| B. napus | 1 257 794 | 20.7 MB | 11.8 MB | 3.1 MB | 3 MB | 835 KB | 27% |
| H. sapiens | 722 407 | 11.5 MB | 5.8 MB | 1.7 MB | 1.6 MB | 395 KB | 23% |
| E. coli | 84 126 | 1.4 MB | 657 KB | 193 KB | 208 KB | 63 KB | 32% |
| A. baumannii | 69 723 | 1.1 MB | 605 KB | 175 KB | 193 KB | 68 KB | 38% |


_[Original comment](https://github.ugent.be/unipept/unipept/issues/539#issuecomment-21997) by @bmesuere on Wed Dec 02 2015 at 14:23._

**Comment by bmesuere** [comment]
As can be seen in the tests, the decrease in parse time more than makes up for the extra decode time.

| Organism | old parse time | new parse time | decode time | new time | speed |
| :-- | --: | --: | --: | --: | --: |
| B. napus | 76.7 ms | 52 ms | 8.1 ms | 60.1 ms | -21% |
| A. baumannii | 8.4 ms | 6.5 ms | 1.8 ms | 8.3 ms | -1% |


_[Original comment](https://github.ugent.be/unipept/unipept/issues/539#issuecomment-21998) by @bmesuere on Wed Dec 02 2015 at 14:53._

**Comment by bmesuere** [comment]
It also works in practice:
before:
![image](https://github.ugent.be/github-enterprise-assets/0000/0007/0000/0860/f3aa4466-9913-11e5-9324-4ce7ed00be36.png)
after:
![image](https://github.ugent.be/github-enterprise-assets/0000/0007/0000/0861/19f7e330-9914-11e5-8281-e80649da2075.png)


_[Original comment](https://github.ugent.be/unipept/unipept/issues/539#issuecomment-22008) by @bmesuere on Wed Dec 02 2015 at 16:46._

**Comment by bmesuere** [comment]
Reduced table size:
old proteome_caches table size: 6 050 824 192
new proteome_caches table size: 1 900 560 384


_[Original comment](https://github.ugent.be/unipept/unipept/issues/539#issuecomment-22009) by @bmesuere on Wed Dec 02 2015 at 17:03._

**Comment by pdawyndt** [comment]
only good news ...


_[Original comment](https://github.ugent.be/unipept/unipept/issues/539#issuecomment-22010) by @pdawyndt on Wed Dec 02 2015 at 17:14._
