### ISSUE TITLE
improve similarity calculation performance

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#550]
The new year brought some inspiration.

With the current code, we first calculate the intersection of the two peptide lists and then use that to calculate the union size and similarities.

While experimenting with the delta encoding, I noticed there was a serious performance impact when creating a new array for the decode step instead of doing an in place decode.

Since we do something similar while calculating the intersection (create new array while iterating over both lists at the same time), performance might suffer similarly. Luckily we have a solution: since we don't need the actual intersection but only its size, we might create a dedicated `intersectionSize` method that only keeps a size counter and not an actual array of elements.

The improvements will probably be twofold:
- incrementing an integer is faster than adding an element to an ever expanding array
- we don't allocate hundreds of arrays that need to be garbage collected

_[Original issue](https://github.ugent.be/unipept/unipept/issues/550) by @bmesuere on Fri Jan 01 2016 at 13:51._
_Closed by @bmesuere on Sat Jan 02 2016 at 17:24._

**Comment by bmesuere** [comment]
Memory indeed plays a big role: the similarity calculation with the current code is about 10 times slower when memory pressure is high. The new code is **2-4 times faster** than the old without any memory pressure. When memory is low however, the new code is **20-30 times faster**.

|  | old code | old code w/ <br> memory pressure | new code |
| :-- | --: | --: | --: |
| 32 \* Acinetobacter baumannii | 450 ms | 4500 ms | 180 ms |
| 11 \* primates | 770 ms | 4200 ms | 200 ms |
| 50 \* E. coli | 1311 ms | 13902 ms | 466 ms |


_[Original comment](https://github.ugent.be/unipept/unipept/issues/550#issuecomment-23578) by @bmesuere on Fri Jan 01 2016 at 14:25._

**Comment by pdawyndt** [comment]
@bmesuere nice


_[Original comment](https://github.ugent.be/unipept/unipept/issues/550#issuecomment-23594) by @pdawyndt on Sat Jan 02 2016 at 16:20._
