### ISSUE TITLE
use machine readable format for proteome information

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#579]
I got an email today from UniProt:

> I presume you have noticed that in the meantime, it is possible to download proteome search results in tab-delimited format.

We now parse the html to fetch the proteome and strain names, using the new format would eliminate this hack.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/579) by @bmesuere on Fri Jun 10 2016 at 17:44._
_Closed by @ninewise on Thu Aug 17 2017 at 16:18._

**Comment by bmesuere** [comment]
@ninewise when going through the open issues, I found this suggestion that would probably be a clean way to get rid of the html2text dependency without hacky regexps?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/579#issuecomment-69812) by @bmesuere on Thu Aug 17 2017 at 15:42._

**Comment by ninewise** [comment]
This would be awesome, I'll check it out. Did they mention where you could download this?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/579#issuecomment-69816) by @ninewise on Thu Aug 17 2017 at 15:48._

**Comment by bmesuere** [comment]
Seems it's only for the actual search results and the fields it returns are limited: http://www.uniprot.org/proteomes/?sort=&desc=&compress=no&query=id:UP000000532&limit=10&force=no&preview=true&format=tab&columns=id,name,organism-id,proteincount,strain

If you also can't find what we need, you may close this issue.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/579#issuecomment-69817) by @bmesuere on Thu Aug 17 2017 at 15:56._
