### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#629]
```
Known moderate severity security vulnerability detected in loofah < 2.2.1 defined in Gemfile.lock.
--
Gemfile.lock update suggested: loofah ~> 2.2.1.
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/629) by @bmesuere on Thu Mar 22 2018 at 09:54._
_Closed by @bmesuere on Mon May 07 2018 at 16:58._

**Comment by beardhatcode** [comment]
I'll check out if `bundle update loofah` breaks something

_[Original comment](https://github.ugent.be/unipept/unipept/issues/629#issuecomment-74725) by @beardhatcode on Thu Mar 22 2018 at 14:08._

**Comment by beardhatcode** [comment]
It doesn't as far as I see

_[Original comment](https://github.ugent.be/unipept/unipept/issues/629#issuecomment-74726) by @beardhatcode on Thu Mar 22 2018 at 14:25._
