### ISSUE TITLE
Cross-Origin Request Blocked in API docs

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept#641]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.unipept.ugent.be/api/v1/pept2prot.json?input[]=. (Reason: CORS request did not succeed).

https://unipept.ugent.be/apidocs/pept2prot#try-it

_[Original issue](https://github.ugent.be/unipept/unipept/issues/641) by @beardhatcode on Wed Jul 04 2018 at 14:04._
_Closed by @beardhatcode on Wed Aug 08 2018 at 17:09._

**Comment by bmesuere** [comment]
I think the CORS should be good, but the certificate wasn't renewed for some reason. This causes a failed request.

_[Original comment](https://github.ugent.be/unipept/unipept/issues/641#issuecomment-78182) by @bmesuere on Wed Jul 04 2018 at 14:16._
