### ISSUE TITLE
Download image by link does not work in IE11

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept#648]
Download image by link does not work in IE11. Right clicking on the image and selecting save image does.

Reproduce by performing an Metaproteomics Analysis and click Save as image > Download as PNG.

https://github.ugent.be/unipept/unipept/blob/5a2f2ec8e0ed8aafbf509abc5881e3b2af328ad0/app/assets/javascripts/utils.js#L271

_[Original issue](https://github.ugent.be/unipept/unipept/issues/648) by @beardhatcode on Fri Aug 17 2018 at 10:33._

**Comment by bmesuere** [comment]
I don't think we want to support IE11 any longer
