### ISSUE TITLE
confused about the taxonomic annotation of peptide

### ISSUE THREAD

**Issue by sjtuyf** [unipept/unipept#8]
Dear professor Mesuere ,
       Thanks for your time to read my question. 
        I used unipept to do taxonomic analysis of peptide by the website, https://unipept.ugent.be/datasets. Then, I got the statistical results of taxonomic annotation proportion in each level. The result implied the annotation proportion of genus was higher than that of order and family. It was so strange. In my opinion, if the peptide annotated by the lower level, it would be annotated by the higher level. I also check the outcome of several peptide. That showed several peptides had the lower annotation，without the higher annotation. Below is an example of one peptide. (I just show some columns of all result).

peptide                           lca                      superkingdom        kingdom            phylum                           class                          order           family                 genus        species
GEWNQLTDNPLLK        Sulfurovum        Bacteria                               Proteobacteria          Epsilonproteobacteria                                             Sulfurovum        

      As it shown，this peptide had genus information，but with missing information in the order and family. So I am wondering if you would like to explain the result, when you have time. 
      At last, hope your project goes well and the best wishes to you.
      I am looking forward to your reply. Thanks a lot.

Yours sincerely
Yafei

**Comment by bmesuere** [comment]
This was answered by email:

> This is simply because of how the NCBI taxonomy works. Some lineages have indeed missing values for some ranks. For example for the peptide you posted, the corresponding taxon in the NCBI taxonomy can be found at https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=265570&lvl=3&lin=f&keep=1&srchmode=1&unlock. If you look at the lineage there, you will indeed also see missing values for order and family.
> 
> I'm afraid there's not a lot we can do to solve this problem. I hope this answers your question, if not, please let me know.
