### ISSUE TITLE
Where can I download LCA results in the new version of Unipept?

### ISSUE THREAD

**Issue by lhuangjs** [unipept/unipept#882]
Hello， I found Unipept updated, congratulations. But I cannot download the results of LCA now. So where can I download LCA results in the new version of Unipept?

Thanks!

**Comment by pverscha** [comment]
Hi there,

Thank you for contacting us. This functionality is not present in the new version of Unipept, but will be included again in the next version. We're sorry for the inconvenience.

**Comment by bmesuere** [comment]
@lhuangjs a fix for this is now live. Can you confirm that this resolves your problem?
