### ISSUE TITLE
add counts to lineage tree

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#91]
add counts (number of hits) to the nodes of the lineage tree; counts may be discarded for nodes with zero hits; this gives an immediate impression of the distribution of the hits among the individual nodes.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/91) by @pdawyndt on Sat Oct 06 2012 at 15:54._
_Closed by @bmesuere on Fri Aug 08 2014 at 14:41._

**Comment by bmesuere** [comment]
maybe switch to the d3-based treeview implementation?


_[Original comment](https://github.ugent.be/unipept/unipept/issues/91#issuecomment-10352) by @bmesuere on Mon Aug 04 2014 at 12:03._

**Comment by bmesuere** [comment]
Other ideas are a tooltip or a dedicated info panel. 
See example at http://www.guardian.co.uk/world/interactive/2012/may/08/gay-rights-united-states


_[Original comment](https://github.ugent.be/unipept/unipept/issues/91#issuecomment-10416) by @bmesuere on Thu Aug 07 2014 at 11:51._
