### ISSUE TITLE
LCA caching for all peptides searched for

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#95]
cache the LCA of all peptides searched for, resulting in a minimal loss of performance if a sample is analysed using the most accurate processing of miscleavages; if this would result in a performance boost, also peptides without any match could be cached; later on this cache might give some insight into miscleavage patterns or the number of unmatched peptides

_[Original issue](https://github.ugent.be/unipept/unipept/issues/95) by @pdawyndt on Sat Oct 06 2012 at 15:57._
_Closed by @bmesuere on Mon Feb 01 2016 at 13:53._

**Comment by bmesuere** [comment]
Since we now update the database every month, this is not worth implementing.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/95#issuecomment-24498) by @bmesuere on Mon Feb 01 2016 at 13:53._
