### ISSUE TITLE
export GO to csv 

### ISSUE THREAD

**Issue by tivdnbos** [unipept/unipept#975]
Hi,

When the Unipept results are downloaded to a csv file, there seems to be an issue with the comma separation. In the header (first row), the different GO classifications are listed (GO (biological process),GO (cellular component),GO (molecular function)), but in the exported results they end up in separate columns where the distinction between the three classes gets lost.

Best,
Tim

**Comment by pverscha** [comment]
Hi Tim,

I'm not entirely sure what you mean. The GO-terms are split amongst three columns according to the domain in which they are classified:

![image](https://user-images.githubusercontent.com/9608686/77733683-9da2de00-7007-11ea-9d8a-19364902c1e3.png)

Can you elaborate, or post an export file in which the issue arises?

Thanks!

**Comment by pdawyndt** [comment]
@pverscha some tools interpret semicolumns (`;`) as a separator instead of commas (`,`); although that foolish if the thing is call COMMA separate values, that might be the reason why things have gone astray for @tivdnbos

**Comment by pverscha** [comment]
@tivdnbos What @pdawyndt mentions might indeed be the issue here. Microsoft Excel's separator depends on the locale-setting of your operating system (and ; is used by default in Belgium).

If you open a new Excel spreadsheet, and click "Data" > "From text", you can select the exported file and chose which delimiter should be used. Does this solve your issue?

**Comment by pverscha** [comment]
After a Skype-conversation with @tivdnbos about this issue, we agreed on adding the possibility to also export to other formats (for example semi-colon based). This could drastically speed up the process of working with these files for some users.

**Comment by pverscha** [comment]
This feature has been released into Unipept.
